### DISCUSSION TITLE
Where can assets exposed through docker container be found?

### DISCUSSION THREAD

**Discussion by c0smicdev** [glanceapp/glance#116] [Help] [answered]
I am running glance on a docker container, where I have exposed a volume, which inside the container is available `/app/assets/`. The directory contains an image `service.png`. I am trying to have a monitor widget as follows:
```yaml
- type: monitor
  cache: 1m
  title: Services
  sites:
    - title: Service
      url: localhost:xxx
      icon: /assets/service.png
```

However, when I launch glance, the image can't be found.

I have tried various locations like `/static/` without success. Where could the asset be found?
