### DISCUSSION TITLE
Homepage to Glance tool

### DISCUSSION THREAD

**Discussion by JackBailey** [glanceapp/glance#132] [Guides and resources]
Hi, I transitioned from Homepage to this recently, and I really like it. I made the site I made to transfer my configs a little prettier and it's usable at https://homepage-to-glance.projects.jackbailey.dev ([Source](https://github.com/JackBailey/HomepageToGlance)). Just wanted to share incase its useful to other people

**Comment by svilenmarkov** [comment]
Hey, that's pretty cool, thanks for making and sharing this! 

I'll pin this to give it more exposure in case other people are looking for something like it.

**Comment by Szymok** [comment]
Good job, thanks to it i definitely move from homepage to glance :D

**Comment by vishalkadam47** [comment]
@JackBailey 
I was wondering how about adding one more option for converting exported `bookmarks.html` from a chrome browser or any browser to glance bookmarks.

or is it a strange idea

**Reply by JackBailey** [reply]
> @JackBailey 
> I was wondering how about adding one more option for converting exported `bookmarks.html` from a chrome browser or any browser to glance bookmarks.
> 
> or is it a strange idea

Yeah I could definitely give it a go, shouldn't take very long

**Comment by mgrimace** [comment]
Does Glance handle env vars similar to homepage? For example, my sonarr service along with most of my homelab services looks like this in homepage:
```yaml
    - Sonarr:
        icon: sonarr.png
        href: https://sonarr.{{HOMEPAGE_VAR_LOCAL}}
#        description: manage TV shows
        server: my-docker
        container: sonarr
        widget:
            type: sonarr
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:8989
            key: {{HOMEPAGE_VAR_SONARR_KEY}}
            enableQueue: true
           
``` 

Update:

Yes, after converting homepage services.yaml:

    - Overseerr:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:5055

to glances.yml:

                  - title: Overseerr
                    url: http://${HOMEPAGE_VAR_SERVER_IP}:5055

I just did a quick find/replace in sublime from `{{` to `${` and `}}` to `}` in my glances.yml. In my compose file, I added the line:
```yaml
    env_file:
      - ./.homepage.env
```
to just kept my existing homepage env vars sheet (e.g., IPs, tokens, etc.)
