### DISCUSSION TITLE
Paperless Widget [PHP]

### DISCUSSION THREAD

**Discussion by DickenSerm** [glanceapp/glance#143] [Guides and resources]
First of all: I don't really have much of a plan for PHP, but it works :D
The code is certainly not the best and maybe someone would like to improve it or program it in a different language, but I still didn't want to withhold it from you:

In this example I display the number of documents with the tag "Eingang" and the tag "TODO".
The documents with the tag "TODO" are listed.
Tag names and document names are linked and open in a new tab.

To see the setting options, simply look at the parameters in the glance.yml

![paperless_glance](https://github.com/glanceapp/glance/assets/77905751/49c37b8e-0cde-492d-a8b8-4271c6b8e72e)

I'm open to any criticism or suggestions for improvement :)

**glance.yml**
```YAML
          - type: extension
            url: http://phpserver/paperless.php
            cache: 1s
            allow-potentially-dangerous-html: true
            parameters:
              title: Paperless # default is Paperless
              server: http://paperlessip:paperlessport # default is '' Must be set
              token: paperlesstoken # default is '' Must be set
              tag1: 1 # default is 1
              tag1_name: Eingang # default is Tag1
              tag2: 9 # default is 2
              tag2_name: TODOs # default is Tag2 
              filelimit: 10 # default is 10
              collapse-after: 3 # default is 5
```

**paperless.php**
```PHP
<?php
$title = $_GET['title'] ?? 'Paperless';
$server = $_GET['server'] ?? '';
$token = $_GET['token'] ?? '';
$tag1 = $_GET['tag1'] ?? 1;
$tag1_name = $_GET['tag1_name'] ?? 'Tag1';
$tag2 = $_GET['tag2'] ?? 2;
$tag2_name = $_GET['tag2_name'] ?? 'Tag2';
$filelimit = $_GET['filelimit'] ?? 10;
$collapseafter = $_GET['collapse-after'] ?? 5;
header('Widget-Title: ' . $title);
header('Widget-Content-Type: html');
function fetch_data($url, $token) {
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        'Authorization: Token ' . $token
    ]);
    $response = curl_exec($ch);
    if ($response === false) {
        echo 'Fehler: ' . curl_error($ch);
        curl_close($ch);
        exit;
    }
    curl_close($ch);
    return json_decode($response, true);
}

$url1 = $server . '/api/documents/?tags__id__all=' . $tag1;
$data1 = fetch_data($url1, $token);
if ($data1 === null || !isset($data1['count'])) {
    echo "Fehler beim Laden der Daten für den ersten Tag.";
    exit;
}
$result_count1 = $data1['count'];

$url2 = $server . '/api/documents/?tags__id__all=' . $tag2;
$data2 = fetch_data($url2, $token);
if ($data2 === null || !isset($data2['count'])) {
    echo "Fehler beim Laden der Daten für den zweiten Tag.";
    exit;
}
$result_count2 = $data2['count'];
?>

<ul class="list-horizontal-text margin-bottom-10">
    <li><a href="<?= $server . '/documents?tags__id__all='. $tag1 .'&sort=created&reverse=1&page=1' ?>" target="_blank"><?= $tag1_name . ': ' ?></a><span class="color-primary"><?= $result_count1 ?></span></li>
    <li><a href="<?= $server . '/documents?tags__id__all='. $tag2 .'&sort=created&reverse=1&page=1' ?>" target="_blank"><?= $tag2_name . ': ' ?></a><span class="color-primary"><?= $result_count2 ?></span></li>
</ul>
<hr>
<ul class="list list-gap-10 collapsible-container" data-collapse-after="<?= $collapseafter ?>">	
    <?php
    $results = array_slice($data2['results'], 0, $filelimit); 
    foreach ($results as $result):
	    $link = $server . '/documents/' . $result['id'] . '/details';
    ?>
        <li class="margin-top-10 list max-width-100">
            <div>
                <div style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">• <a class="color-primary-if-not-visited" href="<?= $link ?>" target="_blank"><?= $result['title'] ?></a></div>
            </div>
        </li>
    <?php endforeach; ?>
</ul>
```
