### DISCUSSION TITLE
Docker containers widget [Go]

### DISCUSSION THREAD

**Discussion by DVDAndroid** [glanceapp/glance#182] [Guides and resources]
Hi all, I've created a custom widget that displays a list of running (or stopped) Docker containers in your machine.

Here's a preview:
![preview](https://raw.githubusercontent.com/DVDAndroid/glance-docker-container-ext/master/assets/screen.png)

Installation and configuration are very simple:
you need to start a new Docker container:
```yaml
  glance-docker-container-ext:
    image: dvdandroid/glance-docker-container-ext:1
    container_name: glance-docker-container-ext
    restart: unless-stopped
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT=8081 # Optional, default is 8081
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

then add in your glance.yml configuration the widget:
```yaml
  - type: extension
    allow-potentially-dangerous-html: true
    url: http://glance-docker-container-ext:8081
    cache: 5m
    parameters:
      title: Docker Containers
      all: true
      order: name,status
```

finally, for every Docker container you want to be visible in the dashboard, you need to add these labels (example):
```yaml
    labels:
      glance.enable: true
      glance.name: Sonarr
      glance.description: TV show search
      glance.url: http://sonarr.lan
      glance.icon: ./assets/imgs/television-classic.svg
```

Repository is available [here](https://github.com/DVDAndroid/glance-docker-container-ext), more details in the README

<sub><sup>it's one of my first Go programs, so contributions or tips are welcome</sup></sub>
