### DISCUSSION TITLE
How do I get a custom css to work?

### DISCUSSION THREAD

**Discussion by ealap** [glanceapp/glance#188] [Help] [answered]
Hi, thanks for this awesome project!

I have deployed this app using Docker compose and have been tinkering with the config for a while. Most features/customizations I have tried works except custom css.

Compose

```compose.yaml
services:
  glance:
    image: glanceapp/glance
    volumes:
      - ./glance.yml:/app/glance.yml
      - ./custom.css:/assets/custom.css
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    restart: unless-stopped

```
glance.yml
```yaml
theme:
  background-color: 249 22 12
  primary-color: 2 55 83
  negative-color: 343 76 68
  contrast-multiplier: 1.2
  custom-css-file: "/assets/custom.css"
```
custom.css
```css
.uppercase {
  text-transform: capitalize;
}
```
But I get 404 response on the request for `/assets/custom.css`.

I also tried pointing it to a public raw gist of the same css. I get 200 response but I get browser errors this time saying "This page failed to load a stylesheet from a URL". I searched elsewhere and this seemed to be cause the response `Content-Type` being `text/plain` instead of `text/css`.
