### DISCUSSION TITLE
How to Configure Dual Domains or IPs for a Single Link as Backup

### DISCUSSION THREAD

**Discussion by Skinsly** [glanceapp/glance#335] [Help]
title: xxx
url: https://xx.xxx.xx/ Can I add two domains or IPs for this kind of url? Sometimes the first address cannot be connected.

**Comment by svilenmarkov** [comment]
Hey, could you please clarify which widget this is related to?

**Comment by Skinsly** [comment]
- type: monitor
          cache: 1m
          title: Services
          sites:
            - title: xxx
              url: https://xx.xxx.xx/

**Comment by svilenmarkov** [comment]
You can change the URL that gets checked:

```yaml
- type: monitor
  cache: 1m
  title: Services
  sites:
    - title: xxx
      url: https://xx.xxx.xx/
      check-url: https://xx.xxx.xx/healthcheck
```
