### DISCUSSION TITLE
server-stats, how to show drives mounted to the docker host?

### DISCUSSION THREAD

**Discussion by mgrimace** [glanceapp/glance#373] [Help] [answered]
How do I show the stats of drives mounted to the host system (e.g., /mnt/media) in server-stats?

I use Glance via docker, on a Debian-based Proxmox LXC. I have an NAS-based media drive mounted to the LXC as /mnt/media via SMB/CIFS for my other media services (e.g., plex, calibre-web, etc). It's usually quite full, and I'd like to show it's available:capacity in my server-stats in glance. At the moment, Glance is only showing the LXC's local storage itself (around 60gb), which I generally don't need.

Compose snippet:

```yaml
services:
   glance:
    image: glanceapp/glance
    container_name: glance
    environment: 
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${DOCKERDIR}/appdata/glance:/app/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    networks:
      - homelab    
    ports:
        - 8088:8080
    labels: 
      com.centurylinklabs.watchtower.enable: "true"
      
networks:
  homelab:
    driver: bridge
    external: true      
```      

Config snippet:

```
          - type: server-stats
            servers:
              - type: local
                name: Services
                hide-swap: true
```                

Thanks folks, these are great updates, I appreciate all the work!

**Comment by svilenmarkov** [comment]
You'd have to mount a directory from one of those drives into the container. It can be empty and read-only:

```yaml
services:
   glance:
    image: glanceapp/glance
    container_name: glance
    volumes:
      - /mnt/media/some-empty-dir:/mnt/media:ro
```

**Reply by mgrimace** [reply]
Ok, I added the volume as a blank directory 'backups' on my media drive, and recreated the container

```yaml
      - /mnt/media/backups:/mnt/media:ro
```
But I still only get the local info, it should have a mostly full 2TB drive:

<img width="547" alt="Screenshot 2025-02-23 at 11 25 19 AM" src="https://github.com/user-attachments/assets/7f4fb4d7-376c-45be-a978-7882008b16a4" />

**Reply by clockwinder** [reply, marked as answer]
And in your `glance.yml` you added the new mountpoint?

https://github.com/glanceapp/glance/blob/main/docs/configuration.md#mountpoints

**Reply by mgrimace** [reply]
> And in your `glance.yml` you added the new mountpoint?
> 
> https://github.com/glanceapp/glance/blob/main/docs/configuration.md#mountpoints

Thank you so much, that was the missing piece for me!
```yaml
          - type: server-stats
            servers:
              - type: local
                name: Services
                hide-swap: true
                hide-mountpoints-by-default: true
                mountpoints:
                  "/mnt/media":
                    hide: false
                    name: media
```
