### DISCUSSION TITLE
Stocks: Rename to "Markets" or add rename possibility & add link

### DISCUSSION THREAD

**Discussion by 0x3e4** [glanceapp/glance#39] [General]
Hey!  
First of all.. hats off! Using your app since day 1 and im so happy with it!  
Regarding the stocks feature.. maybe it would be better to rename it to "Markets" or make it possible to rename the title because Yahoo Finance supports other tickers than stocks too (etf, crypto, index,..) and also make it possible to directly link to the Yahoo Finance source.. so its easier to view other details for the listed stock.

![grafik](https://github.com/glanceapp/glance/assets/36382915/33657fd4-9205-4718-8157-1469a9a06f1b)

**Comment by svilenmarkov** [comment]
Hey, thanks and glad to hear you've been happy with Glance!

Perhaps it's a little buried in the docs and I could've put more emphasis on it or phrased it better, but there are some [shared properties](https://github.com/glanceapp/glance/blob/main/docs/configuration.md#shared-properties) available on all widgets, `title` being one of them, which allows you to set a custom title for every widget. With it, you can do stuff like this:

![image](https://github.com/glanceapp/glance/assets/7613769/645f1d4a-33bd-4618-a762-217fcf8743e8)

Here's the config for that:

<details>
  <summary><code>glance.yml</code></summary>
  
```yaml
widgets:
  - type: stocks
    title: Indices
    stocks:
      - symbol: SPY
        name: S&P 500
      - symbol: DX-Y.NYB
        name: Dollar Index

  - type: stocks
    title: Crypto
    stocks:
      - symbol: BTC-USD
        name: Bitcoin
      - symbol: ETH-USD
        name: Ethereum

  - type: stocks
    sort-by: absolute-change
    stocks:
      - symbol: NVDA
        name: NVIDIA
      - symbol: AAPL
        name: Apple
      - symbol: MSFT
        name: Microsoft
      - symbol: GOOGL
        name: Google
      - symbol: AMD
        name: AMD
      - symbol: RDDT
        name: Reddit
      - symbol: AMZN
        name: Amazon
      - symbol: TSLA
        name: Tesla
      - symbol: INTC
        name: Intel
```
</details>

As for linking to Yahoo Finance, I think it might be an even better option to allow you to set a custom link when clicking on the symbol as well as when clicking on the chart, to for example take you to Trading View. I'll try and get that done for the next version, thanks for the idea!
