### DISCUSSION TITLE
Access other services on host

### DISCUSSION THREAD

**Discussion by crosspolar** [glanceapp/glance#400] [Help]
I have changedetection running on the same server within another container on my linux server on port 5001. How can I access it? In my understanding it would be
```
- name: Home
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday
        - type: change-detection
          instance-url: http://host.docker.internal:5001
          token: token
```

and
```
services:
  glance:
    container_name: glance
    image: glanceapp/glance
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      # Optionally, also mount docker socket if you want to use the docker containers widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8060:8080
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

but the widget gives me
```
could not fetch list of watch UUIDs: Get "http://host.docker.internal:5001/api/v1/watch": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by svilenmarkov** [comment]
If changedetection is running in another container then you'd have to put both containers on the same network (unless you also have a proxy) and use the container's name as the domain:

```
instance-url: http://changedetection:5001
```

(or whatever the name of the container is)

**Comment by crosspolar** [comment]
that works, thank you
```
services:
  glance:
    container_name: glance
    image: glanceapp/glance
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      # Optionally, also mount docker socket if you want to use the docker cont>
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: .env
    network_mode: "host"
    restart: unless-stopped
```
