### DISCUSSION TITLE
homepage-dev

### DISCUSSION THREAD

**Discussion by dev-project-us** [glanceapp/glance#406] [Help]
Hello, 
I just installed this dashboard which looks amazing. I was wondering how I could integrate my homepage-dev dashboard as a second page I saw it on youtube with techdox? I tried copying my services.yml as a second page but it didn't work. Could anybody help? 

Thanks a lot

**Comment by luvablemarmot** [comment]
this is the code i have in my glance.yml

```
- name: GetHomePage (or whatever you want to call it)
    columns:
      - size: full
        widgets:
          - type: iframe
            source: "https://homepage.example.com"
            height: 850
```

it will look like this (i used it to test all the dashboards)

<img width="426" alt="Screenshot 2025-03-23 at 10 03 13 AM" src="https://github.com/user-attachments/assets/3745372c-93f0-4102-b49c-723fcdf34adc" />
