### DISCUSSION TITLE
docker-containers

### DISCUSSION THREAD

**Discussion by gehrleib** [glanceapp/glance#501] [Help] [answered]
The documentation on how to use docker-containers isn't clear. 

I've configured my volumes as /var/run/docker.sock:/var/run/docker.sock and got this to work:

```
- type: docker-containers
            hide-by-default: false
```

![image](https://github.com/user-attachments/assets/13c1e114-7241-4a29-bdda-57911be211dc)

However, how do I change the icons? I've tried different variation of this but it does nothing:

```
- type: docker-containers
  hide-by-default: false
  services:
    Glance:
      image: glanceapp/glance:latest
      labels:
        glance.hide: false
        glance.name: Glance
        glance.icon: di:glance
        glance.url: https://http://192.168.1.109:8060/
        glance.description: Dashboard
```

**Comment by stripedew** [comment, marked as answer]
You configure the labels inside your docker-compose.yml files for each container, not in the glance.yaml config file. 
So if it's for glance, you would do:

```
services:
  glance:
    container_name: glance
    image: glanceapp/glance
    volumes:
      - ./config:/app/config
    ports:
      - 8080:8080`
    labels:
        glance.hide: false
        glance.name: Glance
        glance.icon: di:glance
        glance.url: https://http://192.168.1.109:8060/
        glance.description: Dashboard
```
