### DISCUSSION TITLE
Auto update after x seconds

### DISCUSSION THREAD

**Discussion by rtmmbarbosa** [glanceapp/glance#511] [General]
It would be nice to have an auto update feature, like in uptime kuma status page, where you have a 5 minute timer and auto update the webpage after it.

Something like this:
![image](https://github.com/user-attachments/assets/bf54fe89-68d3-45e3-8f46-d91dadc550f8)

What do you think of it?

**Comment by svilenmarkov** [comment]
Hey, there are no plans to implement this, however if you really wanted it you can achieve the same functionality via a simple:

```yaml
document:
  head: |
    <meta http-equiv="refresh" content="300">
```
