### DISCUSSION TITLE
ArchiSteamFarm log

### DISCUSSION THREAD

**Discussion by Paul-16098** [glanceapp/glance#536] [Guides and resources]
```yml
          - type: custom-api
            title: ASF log
            title-url: ${ASF_URL}/log
            cache: 1s
            url: ${ASF_URL}/Api/NLog/File
            headers:
              Authentication: ${ASF_PASSWORD}
            parameters:
              count: 15
            template: |
              <div>
              {{ range .JSON.Array "Result.Content" }}
              {{ $v := (.String "" | trimSpace) }}
              <div style="display: grid;grid-template-columns: auto auto 1fr;line-height: 1.1;margin: 0 0 .1em;width: 100%;">{{ $v | printf }}</div>
              {{ end }}
              </div>
```
![image](https://github.com/user-attachments/assets/9d52d3fd-1197-4f3e-a933-ee7470718346)
