### DISCUSSION TITLE
GitHub Stats

### DISCUSSION THREAD

**Discussion by Paul-16098** [glanceapp/glance#538] [Guides and resources]
```yml
          - type: extension
            title: GitHub Stats
            url: https://github-readme-stats.vercel.app/api
            allow-potentially-dangerous-html: true
            fallback-content-type: html
            parameters:
              username: ${GITHUB_USERNAME}
              show_icons: true
              count_private: true
```
![image](https://github.com/user-attachments/assets/05dc5162-8a24-431b-8472-4e9921ca17b9)
