### DISCUSSION TITLE
GitHub top-langs

### DISCUSSION THREAD

**Discussion by Paul-16098** [glanceapp/glance#539] [Guides and resources]
```yml
          - type: extension
            title: GitHub top-langs
            url: https://github-readme-stats.vercel.app/api/top-langs
            allow-potentially-dangerous-html: true
            fallback-content-type: html
            parameters:
              username: ${GITHUB_USERNAME}
              show_icons: true
              count_private: true
```
![image](https://github.com/user-attachments/assets/7da9674d-0431-48d4-9628-b79e7e71184a)
