### DISCUSSION TITLE
wakatime

### DISCUSSION THREAD

**Discussion by Paul-16098** [glanceapp/glance#540] [Guides and resources]
```yml
          - type: extension
            title: wakatime
            url: https://github-readme-stats.vercel.app/api/wakatime
            allow-potentially-dangerous-html: true
            fallback-content-type: html
            parameters:
              username: ${WAKATIME_USERNAME}
              show_icons: true
              count_private: true
```
![image](https://github.com/user-attachments/assets/527d834c-bd78-4ed2-84f5-e53b846761f5)
