### DISCUSSION TITLE
Glance agent status?

### DISCUSSION THREAD

**Discussion by ricjuhnl** [glanceapp/glance#581] [Help] [answered]
Following the docs for remote server statistics, it tells me i need to run a glance agent:

> To display data from a remote server you need to have the Glance Agent running on that server

But the link returns a 404:
https://github.com/glanceapp/agent

Is the agent deprecated? And how can i monitor stats from multiple servers?

**Comment by kubakubakuba** [comment, marked as answer]
I made a simple working agent running in docker here: [https://github.com/glanceapp/glance/discussions/398](https://github.com/glanceapp/glance/discussions/398), but for now, there is no official way i think.
Multiple servers can be simply done by:
```yaml
servers:
  - type: local
    name: Local
  - type: remote
    name: Alpha
    url: http://alpha.server.com:8080
    token: <password>
  - type: remote
    name: Beta
    url: http://beta.server.com:8080
    token: <password>
  - type: remote
    name: Gamma
    url: http://gamma.server.com:8080
    token: <password>
```
