### DISCUSSION TITLE
HTML bullet lists

### DISCUSSION THREAD

**Discussion by roughnecks** [glanceapp/glance#601] [General]
Hi,

I'm trying to make a bullet list in the HTML widget, to no avail. I'm pretty sure the code (tags) are okay, but it just doesn't show up, in fact I get only paragraphs and no errors from glance.

**Comment by svilenmarkov** [comment]
The default styles for most elements have been removed, so you'd need to add your own custom CSS:

```css
.bullet-list {
  margin-left: 2rem;
  list-style: initial;
}
```

```html
<ul class="bullet-list">
  <li>Example 1</li>
  <li>Example 2</li>
  <li>Example 3</li>
</ul>
```
