### DISCUSSION TITLE
v4 release

### DISCUSSION THREAD

**Discussion by hxck** [glanceapp/glance#62] [General]
How did you get the monitored sites to stack horizontally instead of in just one long vertical row?

**Comment by svilenmarkov** [comment]
Hey,

You have to set the style of your widget to `dynamic-columns-experimental`.

```yaml
- type: monitor
  style: dynamic-columns-experimental
  sites: ...
```
