### DISCUSSION TITLE
How to track indexs on "Markets" widget

### DISCUSSION THREAD

**Discussion by karanravindra** [glanceapp/glance#621] [Help]
Im trying to track the VIX index but it's not working for some reason. How does `glance` pull the stock info?

```yml
- type: markets
  markets:
    - symbol: VIX
      name: VIX
      chart-link: https://www.tradingview.com/chart/?symbol=INDEX:VIX
```
