### DISCUSSION TITLE
RSS feeds and the "type: group" property

### DISCUSSION THREAD

**Discussion by j74s** [glanceapp/glance#636] [Help]
Hi all, I have been trying to use the "type: group" property with rss feeds so they are arranged in tabs but without any success.

```
- size: full
        widgets:
          - type: group
            widgets:           
          - type: rss
            feeds:
              - url: http://feeds.bbci.co.uk/news/world/rss.xml    
          - type: rss              
            feeds:
              - url: https://www.euronews.com/rss
```

Am I missing something? Thanks for any help.

**Comment by svilenmarkov** [comment]
Hey, it looks like your formatting might be wrong, the two RSS widgets need to be under the `widgets:` property of the `group`:

```yaml
- size: full
  widgets:
    - type: group
      widgets:           
        - type: rss
          feeds:
            - url: http://feeds.bbci.co.uk/news/world/rss.xml    
        - type: rss              
          feeds:
            - url: https://www.euronews.com/
```
