### DISCUSSION TITLE
How to spillover long lists into multiple columns?

### DISCUSSION THREAD

**Discussion by mgrimace** [glanceapp/glance#638] [Help]
Hello, at the moment I have one long markets list with multiple tickers. I'd like that to spill across three columns on a page, rather than have one long column. Is there a way to do this automatically vs., manually splitting it up into three lists?

**Comment by mgrimace** [comment]
Oh, nevermind! it did it with the following:

```yaml
- name: Stocks
    width: slim
    #hide-desktop-navigation: true
    center-vertically: true
    columns:
      - size: full
        widgets:
          - type: split-column
            max-columns: 3
            widgets:
              - type: markets
                markets:
```
