### DISCUSSION TITLE
Authentication stopped working

### DISCUSSION THREAD

**Discussion by Kamush999** [glanceapp/glance#682] [Help] [answered]
I set up authentication and everything worked for a few hours. But at one moment it just stopped letting through, although the login and password were correct. The page just reloads, there are no logs, no errors either. I run it in a docker container. 

```
pages:
  $include: main.yml
  $include: articles.yml
  $include: youtube.yml
  $include: template.yml

theme:
  presets:
    neon-focus:
      background-color: 255 14 6
      primary-color: 156 50 65
      negative-color: 342 65 65
      contrast-multiplier: 0.9 
      text-saturation-multiplier: 0.8
      
branding:
  logo-url: /assets/favicon-32x32.png
  favicon-url: /assets/favicon.ico
  hide-footer: true

server:
  proxied: true
  assets-path: /app/assets
  base-url: https://site.com
  port: 8080

auth:
  secret-key: secret-key
  users:
    user:
      password: 123456
```

```
services:
#-------------------------------------------------------------------#
  glance:
    container_name: glance
    image: glanceapp/glance:latest
    labels:
      glance.hide: true
    volumes:
      - ../config/glance:/app/config
      - ../config/glance/assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      - GLANCE_USERNAME=${GLANCE_USERNAME}
      - GLANCE_PASSWORD=${GLANCE_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - proxy-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
#-------------------------------------------------------------------#
networks:
  proxy-network:
    driver: bridge
```
