### DISCUSSION TITLE
Trouble with the Docker Containers Widget

### DISCUSSION THREAD

**Discussion by mtwb47** [glanceapp/glance#692] [Help] [answered]
Hello there,

I'm having issues with the Docker Container widget. I keep getting this error, and I'm unsure why.

`fetching containers: sending request to socket: Get "http://docker/containers/json?all=true": dial unix /var/run/docker.sock: connect: no such file or directory`

`/var/run/docker.sock'  does exist, I checked. Here is my compose file. 

```

services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - /srv/dockerdata/glance/config:/app/config
      - /srv/dockerdata/glance/assets:/app/assets
      # Optionally, also mount docker socket if you want to use the docker containers widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8084:8080
    env_file: .env

```

I did have to change ports, I'm not sure if that's the reason I'm getting the error.
