### DISCUSSION TITLE
Format date time with local timezone

### DISCUSSION THREAD

**Discussion by devmatteini** [glanceapp/glance#704] [Help]
Hi!

I'm using the `custom-api` widget where my API is returning a JSON with a `date` property which is a ISO8601 formatted date:
```json
{
    "date": "2025-05-26T17:38:48.641Z"
}
```

I would like to display that date in the local timezone. For example, using Europe/Rome as timezone, and this layout `02/01/2006 15:04:05 MST` (from go docs), I would expect this string `26/05/2025 19:38:48 CEST`, but it renders this instead `26/05/2025 17:38:48 UTC` where the local timezone is ignored.

My test glance.yml file:
```yaml
pages:
  - name: Home
    columns:
      - size: full
        widgets:
          - type: custom-api
            title: Test
            url: http://127.0.0.1:8888/
            template: |
              <div>{{ .JSON.String "date" | parseLocalTime "rfc3339" | formatTime "02/01/2006 15:04:05 MST" }}</div>
```

With my very basic Go skills, I changed the `customAPIFuncParseTimeInLocation` implementation to make it work.
```diff
func customAPIFuncParseTimeInLocation(layout, value string, loc *time.Location) time.Time {
	switch strings.ToLower(layout) {
	case "unix":
		asInt, err := strconv.ParseInt(value, 10, 64)
		if err != nil {
			return time.Unix(0, 0)
		}

		return time.Unix(asInt, 0)
	case "rfc3339":
		layout = time.RFC3339
	case "rfc3339nano":
		layout = time.RFC3339Nano
	case "datetime":
		layout = time.DateTime
	case "dateonly":
		layout = time.DateOnly
	}

-	parsed, err := time.ParseInLocation(layout, value, loc)
+	parsed, err := time.Parse(layout, value)
	if err != nil {
		return time.Unix(0, 0)
	}

-	return parsed
+	return parsed.In(loc)
}
```

I'm not sure if this is a bug or how it was intended to work. 

Let me know if there is another way to solve this issue or if I should open a PR!
