### DISCUSSION TITLE
At Releases, how can I configure to check new releases from Github: ghcr.io ?

### DISCUSSION THREAD

**Discussion by edersong** [glanceapp/glance#707] [General]
At Releases, how can I configure to check new releases from Github: ghcr.io ?
Tried those options without luck:
```
- type: releases
  show-source-icon: true
  collapse-after: 20
  repositories:
    - github:hoarder-app/hoarder:latest
    - ghcr.io/hoarder-app/hoarder
    - ghcr.io/hoarder-app/hoarder:latest
    - ghcr.io:hoarder-app/hoarder
```
