### DISCUSSION TITLE
Background Image

### DISCUSSION THREAD

**Discussion by hxck** [glanceapp/glance#88] [General]
Looking through the config options for themes only shows a HSL value for background-color, but not a way to use an image. Is this not implemented, or just not documented?

**Comment by svilenmarkov** [comment]
It's not currently implemented. If you're comfortable with CSS you can still add a background image via the `custom-css-file` property and something like:

```css
body {
    background-image: url("<url to image>");
    background-size: cover;
    background-attachment: fixed;
}
```

Though it most likely won't look all that good since the rest of the design wasn't made with background images in mind. I do want to add proper support for it at some point but I'm prioritizing adding new widgets for now.
