### ISSUE TITLE
[Bug] Piped feed don't show thumbnails

### ISSUE THREAD

**Issue by Generator** [glanceapp/glance#127]
### Description 

RSS from Piped instances (e.g. https://piped.video) 

```
          - type: rss
            style: detailed-list
            title: Piped
            collapse-after: 3
            feeds:
              - url: https://pipedapi.kavin.rocks/feed/rss?authToken=<token>

```

screenshot:
![Screenshot 2024-06-04 at 13-36-04 Home - Glance](https://github.com/glanceapp/glance/assets/44146/bcdbd040-7ea8-47c7-8e17-b54b564d3731)
