### ISSUE TITLE
Feature Request - Different URLs for monitor widget

### ISSUE THREAD

**Issue by MrExplode** [glanceapp/glance#154]
I would like to set different URLs for status checking and the UI link, something like this:
```yml
- type: monitor
  cache: 1m
  title: Services
  sites:
    - title: Jellyfin
      check: https://jellyfin.yourdomain.com/health
      link: https://jellyfin.yourdomain.com
      icon: /assets/jellyfin-logo.png
```
