### ISSUE TITLE
[Feature Request] Widget groups

### ISSUE THREAD

**Issue by VeryEvilHumna** [glanceapp/glance#169]
Ability to group multiple widgets in one place and use tabs to switch between them would be very useful! + shared config between grouped widgets, to keep things DRY

### News group

```yaml
# glance.yml

pages:
  - name: Home
    columns:
      - size: full
        widgets:
          - type: group
            shared-props:
              limit: 15
              collapse-after: 5
            widgets:
              - type: lobsters
                sort-by: hot
              - type: hacker-news
              - type: reddit
                subreddit: selfhosted
              - type: rss
                title: RSS Feed
```

![image](https://github.com/user-attachments/assets/cc0e4c7d-4ea7-4a50-ae89-65e04c71a9f5)

### Reddit group
```yaml
# glance.yml

pages:
  - name: Home
    columns:
      - size: full
        widgets:
          - type: group
            shared-props:
              limit: 15
              collapse-after: 5
              sort-by: top
              top-period: week
            widgets:
              - type: reddit
                subreddit: selfhosted
              - type: reddit
                subreddit: unixporn
              - type: reddit
                subreddit: web_design
                top-period: month # <= will override shared props
```
![image](https://github.com/user-attachments/assets/b8f3e01a-6688-4ec2-9b38-e48757801d54)
