### ISSUE TITLE
Not all releases are displayed

### ISSUE THREAD

**Issue by jbeckman1974** [glanceapp/glance#187]
Below is a section of my glance_config.yml file using "releases".  Of the below, only advplyr/audiobookshelf, jc21/nginx-proxy-manager and glanceapp/glance show up.  I verified they show up like that on hub.docker.com.  I even tried putting ghcr.io/ in front of the hotio and lscr.io/ in front of the linuxserver containers but I can't get any of them to show up.  What am I missing?  Is there something I'm missing?  I added the "limit: 20" section because I thought maybe it was limited to 3 but that doesn't seem to change anything.

Here is the display of the below code:
![image](https://github.com/user-attachments/assets/9e35a043-d8d7-4fc3-ba34-c8d40b92ed0b)

```
          - type: releases
            token: < my token >
            limit: 20
            repositories:
              - advplyr/audiobookshelf
              - jc21/nginx-proxy-manager
              - pihole/pihole
              - favonia/cloudfare-ddns
              - portainer/portainer-ce
              - wordpress
              - redis
              - mysql
              - hotio/lidarr
              - hotio/overseerr
              - hotio/radarr
              - hotio/readarr
              - hotio/sonarr
              - hotio/sabnzbd
              - glanceapp/glance
              - linuxserver/bookstack
              - linuxserver/mariadb
              - linuxserver/thelounge
```
