### ISSUE TITLE
Assets aren't loaded

### ISSUE THREAD

**Issue by avivi55** [glanceapp/glance#189]
First of all, nice job it's beautiful.

I am using the personnaly compiled version after a git clone of the `main` branch.
I also tried the precompiled binary from `release v0.5.0` and same problem.

It worked fine on the docker version (by mounting the same directory), but I don't wish to use docker.

The problem is that the `assets-path` is shown to be correctly set, but when trying to load icons they don't show/don't exist.

This is the `glance.yaml` part 
```yaml
server:
  host: 127.0.0.1
  port: 8080
  assets-path: assets

...

          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: WTFPL
                url: http://www.wtfpl.net/
                icon: /assets/wtfpl.ico
```

```
$ go run .
2024/08/08 16:28:17 INFO Serving assets path=/home/user/Documents/glance/assets
2024/08/08 16:28:17 INFO Starting server host=127.0.0.1 port=8080
```

```
$ tree /home/user/Documents/glance/assets
/home/user/Documents/glance/assets
└── wtfpl.ico
```

But this is what I get in the glance page
![icon](https://github.com/user-attachments/assets/8bae291c-51d3-4841-a389-ce999701b0f4)
![error](https://github.com/user-attachments/assets/d1eeac2f-8de5-4f3c-b876-bc41187158c4)

I tried with an absolute path, it doesn't change anything.
I compiled it an run the executable instead of `go run`, still the same.

Thank you for your consideration.
