### ISSUE TITLE
Rss Feed Filter

### ISSUE THREAD

**Issue by Chrissi2812** [glanceapp/glance#191]
Would be awesome to have the possibilty to filter the rss feeds on arbitary fields.

Something like this
```yaml

- type: rss
  title: News
  style: horizontal-cards
  feeds:
    - url: https://feeds.bloomberg.com/markets/news.rss
      title: Bloomberg
      filters: # adding this Filter
        - field: title
          value: /Alert/i # RegEx or Just string?
        - field: category
          value: Business
    - url: https://feeds.feedburner.com/crunchyroll/rss/anime?lang=deDE
      title: Crunchyroll
      filters:
        - field: crunchyroll:seriesTitle # or just seriesTitle or extensions.seriesTitle ? Don't know how they get parsed by gofeed
          value: # Here the values should be combined by OR because they would never match both
            - /Failure Frame/i # if matched
            - Berserk of Gluttony # Exact Value
```

**Comment by svilenmarkov** [comment]
Hey, thanks for the idea!

I've actually been thinking about this exact same thing for the last week or so. 😅 Not sure if regular expressions are the way to go or something more advanced like [expr-lang/expr](https://github.com/expr-lang/expr) which would give a ton more flexibility in what you can do.

**Comment by Chrissi2812** [comment]
That [expr-lang/expr](https://github.com/expr-lang/expr) looks way better than what I had on my mind. 
And the syntax is pretty easy to understand just converted my example from above.

```yaml
- url: https://feeds.feedburner.com/crunchyroll/rss/anime?lang=deDE
  title: Crunchyroll
  filter: "{lower(.title) matches 'failure frame'})" # Not sure on quotes ^^
```

And that results in ```filter(entries, {.title matches 'failure frame'}))```

Also could be useful for other parts as well like #148
