### ISSUE TITLE
[Feature Request] Separate URL for checking availability and redirecting on click in monitoring widget

### ISSUE THREAD

**Issue by kubisgg** [glanceapp/glance#198]
I'm using AdGuard Home for DNS rewrites, but when I insert a URL with a domain to monitor my site, I get the error "1.1.1.1:53 no such host". My idea for this: add optional property, for example `url-target` which, when clicked, will redirect to a specific URL while the glance continues to check for IP availability.

```yaml
- type: monitor
  cache: 1m
  sites:
    - title: Zabbix
      url: http://10.0.5.3
      url-target: https://zabbix.domain.home # <- optional property, targeting to different URL than checked above
      icon: /assets/zabbix-logo.png
    - title: AdGuard Home
      url: http://10.0.5.5
      url-target: https://adguard.domain.home
      icon: /assets/adguard-logo.png
    - title: Pterodactyl
      url: https://pterodatyl.domain.com # <- site without optional property, redirecting to the same URL that is checked
      icon: /assets/pterodactyl-logo.png
```
