### ISSUE TITLE
[Feature Request] - Reusable widgets.

### ISSUE THREAD

**Issue by moonstar-x** [glanceapp/glance#233]
Hi, thanks for this brilliant project, I love it!

In my own instance I'm looking to have multiple pages, and some of them share the same widgets across multiple pages.

Currently I would have to copy-paste the widgets in each page's definition but it can be a bit difficult to update them in the future since I would have to make changes everywhere I use them.

It'd be cool if I could define widgets outside the `pages` definition so that I could reference them instead. An example of what a configuration file would look like:

```yml
widgets:
  reusable-clock:
    type: clock
    timezones:
      - timezone: America/Los_Angeles
        label: Los Angeles
      - timezone: America/New_York
        label: New York

pages:
  - name: Page 1
    columns:
      - size: full
        widgets:
          - type: reference
            key: reusable-clock
  - name: Page 2
    columns:
      - size: full
        widgets:
          - type: reference
            key: reusable-clock
```

Thanks, let me know what you think, if I have some free time off work I could probably cook up a PR but my Go skills are a bit rusty. 😄

**Comment by svilenmarkov** [comment]
Thanks for the kind words!

You can already do this using YAML anchors, which you can read more about [here](https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/) and [here](https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd).

Here's a slightly modified version of the example you provided that uses them:

```yaml
widgets:
  - &reusable-clock
    type: clock
    timezones:
      - timezone: America/Los_Angeles
        label: Los Angeles
      - timezone: America/New_York
        label: New York

pages:
  - name: Page 1
    columns:
      - size: full
        widgets:
          - <<: *reusable-clock
  - name: Page 2
    columns:
      - size: full
        widgets:
          - <<: *reusable-clock
```
