### ISSUE TITLE
Markets widget rendering issue

### ISSUE THREAD

**Issue by bloomberg21** [glanceapp/glance#239]
Using snippet for markets from the examples listed:
```
- name: Markets
    columns:
      - size: small
        widgets:
          - type: markets
            title: Indices
            markets:
              - symbol: SPY
                name: S&P 500
              - symbol: DX-Y.NYB
                name: Dollar Index

          - type: markets
            title: Crypto
            markets:
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: ETH-USD
                name: Ethereum

          - type: markets
            title: Stocks
            sort-by: absolute-change
            markets:
              - symbol: NVDA
                name: NVIDIA
              - symbol: AAPL
                name: Apple
              - symbol: MSFT
                name: Microsoft
```

result looks like:
![image](https://github.com/user-attachments/assets/f1af6f6a-22aa-4cf1-8d48-95a47b8e6e08)
