### ISSUE TITLE
User agent for glance

### ISSUE THREAD

**Issue by lunik1** [glanceapp/glance#253]
I have been informed by the team at OpenRSS that subscribing to one of their RSS feeds using an application that does not identify itself by its user agent is a violation of is terms of service. Would it be possible for glance to set its user agent to something like
```
glance / v0.6.2 https://github.com/glanceapp/glance
```
The current user agent is
```
Gofeed/1.0
```

**Comment by svilenmarkov** [comment]
Hey, with v0.7.0 you can now specify custom headers for each individual feed:

```yaml
- type: rss
  feeds:
    - url: https://domain.com/rss
      headers:
        User-Agent: Custom User Agent
```
