### ISSUE TITLE
[Request] Add an !include <file> like what Home Assistant does for the config.

### ISSUE THREAD

**Issue by Krojack** [glanceapp/glance#254]
Currently in Home Assistant you can include other YML files to help keep things somewhat clean.

Small example:
```
pages:
  - name: Home
    columns:
      - size: small
        widgets: !include page-1-widgets-left.yml
      - size: full
        widgets: !include page-1-widgets-middle.yml
      - size: small
        widgets: !include page-1-widgets-right.yml
  - name: Bookmarks
    columns:
      - size: small
        widgets: !include page-2-widgets-left.yml
      - size: full
        widgets: !include page-2-widgets-middle.yml
      - size: small
        widgets: !include page-2-widgets-right.yml
```
This would then load the contents of _page-1-widgets-left.yml_ in that spot.

Rather than have everything in one large file, you could break things down into separate files.
