### ISSUE TITLE
[Request] Allow Tabs for different bookmark groups

### ISSUE THREAD

**Issue by sriramsv** [glanceapp/glance#257]
Allow us to have different bookmark groups in horizontal tabs similar to page tabs so that we dont have to scroll through multiple lists on the home page.

**Comment by svilenmarkov** [comment]
Hey, if I understand correctly, I believe you can already do this using the [`group`](https://github.com/glanceapp/glance/blob/main/docs/configuration.md#group) widget:

```yaml
- type: group
  widgets:
    - type: bookmarks
      title: Group 1
      groups:
        - links:
            - title: Youtube
              url: https://www.youtube.com/

    - type: bookmarks
      title: Group 2
      groups:
        - links:
            - title: Github
              url: https://github.com/
```

![image](https://github.com/user-attachments/assets/00e5bffa-abfd-453a-a1dd-7e97f4dc8cd9)
