### ISSUE TITLE
Add `same-tab` property of Bookmarks for widgets or group levels

### ISSUE THREAD

**Issue by K0ng2** [glanceapp/glance#270]
```yaml
type: bookmarks
groups:
  - title: Social
    same-tab: true
    links:
      - title: Reddit
        url: https://www.reddit.com/
      - title: Twitter
        url: https://twitter.com/
      - title: Instagram
        url: https://www.instagram.com/
      - title: Facebook
        url: https://www.facebook.com/
````
or
```yaml
type: bookmarks
same-tab: true
groups:
  - title: Social
    links:
      - title: Reddit
        url: https://www.reddit.com/
      - title: Twitter
        url: https://twitter.com/
      - title: Instagram
        url: https://www.instagram.com/
      - title: Facebook
        url: https://www.facebook.com/
````
