### ISSUE TITLE
Different sized navbar and content

### ISSUE THREAD

**Issue by ilovethensa** [glanceapp/glance#271]
Can you add support for differently sized navbar and content, for example my content could be slim and my bar full

**Comment by svilenmarkov** [comment]
Hey, no plans to add this for now but you can easily do it with a bit of [custom CSS](https://github.com/glanceapp/glance/blob/main/docs/configuration.md#custom-css-file):

```css
.header-container {
    /* the width can be anything you like */
    max-width: 1920px;
}
```
