### ISSUE TITLE
[Feature request] Support for env vars in monitor, bookmarks widgets

### ISSUE THREAD

**Issue by mgrimace** [glanceapp/glance#273]
Hello, this request is to support inline env vars for both the monitor and bookmarks widgets. 

The use-case is to avoid putting IPs or personal domains in plain-text on the glances.yml. This is useful for sharing configs/setups without having to redact information, and ideally safer practices. This is useful particularly if a user is using bookmarks or monitor to show homelab services.

For example, 
```yaml
                  - title: Overseerr
                    url: http://${SERVER_IP}:5055
                    icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/overseerr.svg
```
or,
```yaml
                 - title: Overseerr
                    url: https://overseer.${PERSONAL_DOMAIN}
                    icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/overseerr.svg
```
This could potentially be useful for sensitive embedded keys, tokens, etc. as well, e.g.,`url: https://connect.raspberrypi.com/devices/${RPI_2_UUID}/remote-shell-session`
