### ISSUE TITLE
Adjust names of widgets in groups

### ISSUE THREAD

**Issue by Catbirby** [glanceapp/glance#276]
Hello,

I was wondering if there is the ability to adjust the names of tabs inside of groups. I wanted to have separated video feed (one for tech one for misc.) but they are both labeled "videos". I was unable to find any way to tweak this within the config file.

![image](https://github.com/user-attachments/assets/d57b07b4-2182-40ab-b07f-00b6022fdf85)

Appreciate the work. This project is awesome!

**Comment by svilenmarkov** [comment]
Hey, there are [a couple of properties](https://github.com/glanceapp/glance/blob/main/docs/configuration.md#shared-properties) that are available on all widgets, `title` being one of them, which you can also use to change the group titles. Here's an example:

```yaml
- type: group
  widgets:
    - type: videos
      title: Tech
      channels: 
        ...
    - type: videos
      title: Misc
      channels: 
        ...
```
