### ISSUE TITLE
Issues with Monitor Widget

### ISSUE THREAD

**Issue by mayanus** [glanceapp/glance#277]
Hello,

This is the tool I've always dreamed about, amazing! The only issue is that when I try to add the monitor widget I get a Timed Out or Error, nevertheless I can reach the site if I click on it. This is mostly an "aesthetic issue". Probably related to #223 

![image](https://github.com/user-attachments/assets/b44cf5c9-bcc1-49f0-b1df-2da968eccd83)

``` yml
pages:
  - name: Home
    hide-desktop-navigation: true
    columns:
      - size: small
        widgets:
          - type: calendar
         
          - type: monitor
            title: Services
            sites:
              - title: Immich
                url: https://immich.home.com
              - title: Jellyfin
                url: https://jellyfin.home.com
              - title: Vaultwarden
                url: https://vaultwarden.home.com

```
Here are the logs

![image](https://github.com/user-attachments/assets/c0f552d2-ee01-490e-af3f-d4389da8fd45)

Using cURL

![image](https://github.com/user-attachments/assets/40477ba3-3d6d-47d7-871f-e93623b8f4ea)

![image](https://github.com/user-attachments/assets/3e8240db-0c02-4dba-8a9c-21ff9e1f45ce)

Happy to help. Thank you for your time.

**Comment by svilenmarkov** [comment]
Hey, thanks for reporting this. Could you provide a bit more information about your setup, like do you have a VPN sitting in between your services? Could you also provide the output of these two commands?

To get an idea of how long it usually takes for the request to complete outside of the container:
```
time curl -s https://immich.{$DOMAIN} -o /dev/null
```

To see if that time matches with the request coming from within the container: 
```
docker exec glance time wget -qSO /dev/null https://immich.{$DOMAIN}
```

**Comment by mayanus** [comment]
Hello,

I do have a VPN using gluetun but I tried stopping the container and it is still Timing Out.

I run a local DNS using Adguard using Traefik as my reverse proxy paired with the tecnativa docker-socket-proxy.

![image](https://github.com/user-attachments/assets/bc23514f-31ae-46ff-b65e-aa937d04d503)

![image](https://github.com/user-attachments/assets/e002c5e1-4961-4761-9ed0-cd99ca2ac7a7)

No output.

**Comment by svilenmarkov** [comment]
Thanks for providing those! Can you repeat this command but run it from within one of your other containers to see if it's an isolated issue with Glance's Docker image?

```
docker exec <container id or name> time wget -qSO /dev/null https://immich.{$DOMAIN}
```

And one more thing, I had a somewhat similar issue a while back which ended up being due to overly restrictive firewall rules, if you have ufw running (or anything of the like), could you try disabling it and seeing if that fixes the issue?

**Comment by mayanus** [comment]
I have the same result running it from another container. No output.
![image](https://github.com/user-attachments/assets/33c1110f-ce3d-4e0c-9251-a7a7a5fa80d3)

Running that command without docker
![image](https://github.com/user-attachments/assets/d1a8e0b7-5f3d-4716-86df-0f512fd2eb97)

Using ping inside the glance container
![image](https://github.com/user-attachments/assets/1182910f-acef-4337-84da-d24a82e44fdf)


My containers are in a network called frontend, using netshoot I can reach immich and glance.
![image](https://github.com/user-attachments/assets/efafc58a-aa12-46f3-adcf-66c8230b8a5b)


For my firewall I use iptables with these rules

```bash
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT
```

Changed all of them to ACCEPT, still the same issue.

Now, the documentation https://github.com/glanceapp/glance/blob/main/docs/configuration.md#monitor

Says

![image](https://github.com/user-attachments/assets/ca3e7015-09a3-4d66-a330-d4840b7d16de)

All my containers are only locally accessible, none of them are public. If I place a public url, the are no errors.

```yaml
pages:
  - name: Home
    hide-desktop-navigation: true
    columns:
      - size: small
        widgets:
          - type: calendar

          - type: monitor
            title: Services
            sites:
              - title: Immich
                url: https://github.com/glanceapp/glance
```
![image](https://github.com/user-attachments/assets/e23048b8-06ed-4615-859c-b28e66a33361)

**Comment by svilenmarkov** [comment]
Since this is also happening from within other containers it is most likely not an issue with Glance itself or the Docker image.

I see that you used the service name when running the ping which worked, but when using your domain name it doesn't. I might be wrong since my knowledge of networking internals is limited, however I believe the two are not the same. When using the service name the request gets routed through Docker's internal interface (172.18.x.x), however when using the domain name it gets resolved to your machine's local network IP (presumably 192.168.x.x), so there are more hops involved. If my theory is correct, since all containers are on the same Docker network you should be able to bypass your reverse proxy and make a request to your immich container directly:

```
docker exec glance wget -qSO /dev/null immich-server:2283
```

As well as use that URL in your glance.yml:

```yaml
- type: monitor
  title: Services
  sites:
    - title: Immich
      url: immich-server:2283
```

**Comment by mayanus** [comment]
Nice! It worked!

![image](https://github.com/user-attachments/assets/769d1f23-5546-4fb6-9d76-d601365bba3d)

I just added http and also used ```check-url``` so ```url``` redirects to the internal url of my reverse proxy.


```yaml
pages:
  - name: Home
    hide-desktop-navigation: true
    columns:
      - size: small
        widgets:
          - type: calendar

          - type: monitor
            title: Services
            sites:
              - title: Immich
                check-url: http://immich-server:2283
                url: https://immich.home.com

```

![image](https://github.com/user-attachments/assets/c281270f-3dd2-45e4-ab1b-9dc0444d7091)

Thanks a lot!
