### ISSUE TITLE
Extension Widget Title

### ISSUE THREAD

**Issue by DallasHoff** [glanceapp/glance#279]
I've set up an extension widget, and I noticed that setting a title in the widget config has no effect if the extension sends a title in the `Widget-Title` header.

```yaml
- type: extension
  title: Foo
  url: http://example.com
```

In this case, I would expect the config to take precedence and make the widget's title render as "Foo" but the header takes precedence instead. Is this intended?

**Comment by svilenmarkov** [comment]
Hey, thanks for bringing this up. I think you have a good point and it is something I overlooked, I'll get it sorted out with the next release so that the title defined in the config takes priority.

**Comment by svilenmarkov** [comment]
Hey @Anachron, I purposefully didn't want to automatically change the repository widget title to the repository name because I wanted to avoid the repetition of:

![image](https://github.com/user-attachments/assets/93c1fafb-6ae8-4f2d-8c58-b55cd6b66228)

Like with all widgets, you can still manually change the title to whatever you like and that title will also be used for groups:

```yaml
- type: group
  widgets:
    - type: repository
      title: Glance Repository
      repository: glanceapp/glance
    - type: repository
      title: Immich Repository
      repository: immich-app/immich
```

![image](https://github.com/user-attachments/assets/95474176-cb4d-4870-90dc-95549a416c6b)

I don't consider this to be a bug, though feel free to open a new issue if you think the behavior could be improved.
