### ISSUE TITLE
bug - other url schemes are not being rendered correctly

### ISSUE THREAD

**Issue by kamilkosek** [glanceapp/glance#282]
What I am trying to achieve is to open VS Code Workspaces on remote machines via the `bookmarks` widget. 

## What works:
```yaml
          - type: html 
            source: |
                  <a href="vscode://vscode-remote/ssh-remote+root@jellystack.kk.local/jellyplist/jellyplist.code-workspace">Worspace</a>
```
It is rendered like this:
![image](https://github.com/user-attachments/assets/de06d169-5ec4-4d6c-8fee-fdb1b40eac8d)

But when adding this url to the bookmarks widget it is rendered to something different:
```yaml
          - type: bookmarks
            groups:
              - title: Code Workspace´s 
                links:
                - title: Jellyplist
                  url: vscode://vscode-remote/ssh-remote+root@jellystack.kk.local/jellyplist/jellyplist.code-workspace
                  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/visual-studio-code.svg
``` 
![image](https://github.com/user-attachments/assets/0b0ebe81-51cb-4d22-a726-56f28dc0d4e5)

I think it is maybe some safety feature from the rendering engine ? Don´t know, never worked with `go`
