### ISSUE TITLE
newlines "\n" and whitespaces are not preserved when the API call is made via extensions. 

### ISSUE THREAD

**Issue by saicharan0112** [glanceapp/glance#285]
I have a js file that returns a certain text with proper formatting and i am running this on a nodejs server. When I use curl to get the response of the API, the formatting of the response is preserved however when I use the extensions feature inside glance, I don't see that anymore. I am new to the world of servers and APIs so I am not sure what exactly I am missing here. Below is the extensions usage snippet from the glance.yml file. Any help is appreciate.

```
        widgets:
        - type: extension
          url: http://192.168.0.109:3000/getAlerts
          parameters:
            state: TX
```

**Comment by svilenmarkov** [comment]
Hey, thanks for reporting this. This is a bug I'll fix for the next release but for the time being you can still return HTML in your extension's content that can contain any formatting you like.

**Comment by saicharan0112** [comment]
Hey, sorry for my late reply and thanks for your reply (and fix! based on the label you added). I did try returning the entire html but all the p tags are retained. I checked earlier issues on this repo and saw the suggestion to use ngnix with some config addition. I am not familiar with ngnix (just enough node js to build serve the js code as an API). If you can suggest any methods, I am happy to try.

**Comment by svilenmarkov** [comment]
In order to be able to serve HTML you need to add two things:

Change your config to also include `allow-potentially-dangerous-html`:
```yaml
- type: extension
  url: http://192.168.0.109:3000/getAlerts
  allow-potentially-dangerous-html: true
  parameters:
  state: TX
```

Assuming you're using Express in your JS file, add the `Widget-Content-Type` header:
```js
res.set('Widget-Content-Type', 'html')
```
