### ISSUE TITLE
The clock widget shows the UTC time at the top, seemingly ignoring the local timezone setting.

### ISSUE THREAD

**Issue by StepinSilence** [glanceapp/glance#296]
After installing and setting up glance in docker, I find the default displayed time at the top of the time widget is always the UTC time, and the document does not show how to modify the timezone of it. It only shows how to add additional timezone into the time widget. The ```/etc/timezone``` in the container stores the correct timezone info but seemingly ignored by glance. 

The "default displayed time at the top of the time widget" refers to the time highlighted by the red underline.
![Screenshot_20250101_182529](https://github.com/user-attachments/assets/aeca0a8f-cd42-4aa0-9dc3-828fac52b2ad)

Installation method: Docker
Used ```compose.yml```:
```yaml
glance:
  image: glanceapp/glance
  volumes:
    - type: bind
      source: /home/undesired/glance.yml
      target: /app/glance.yml
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
  restart: unless-stopped
```
Content of ```/etc/timezone``` in the container retrieved by ```docker exec <glance-container-name> cat /etc/timezone```:
```
Australia/Melbourne
```
