### ISSUE TITLE
Allow HTTP Basic access authentication in monitor

### ISSUE THREAD

**Issue by logoff** [glanceapp/glance#316]
Current configuration of Monitor sites do not allow HTTP Basic access authentication. It will be very useful allowing it, so some secured sites can be monitored too.

**Comment by ejsadiarin** [comment]
Hey, I added a pull request in `dev` branch for this feature.  So it can be used like this:
```yaml
- title: Traefik
  url: https://traefik.example.com
  icon: di:traefik
  basic-auth:
    username: your-username
    password: your-password
```

As of now on v0.7.2, a workaround is to use `alt-status-codes` (array) and add `401` (Unauthorized) and/or `403` (Forbidden) like so:

```yaml
- title: Traefik
  url: https://traefik.example.com
  icon: di:traefik
  alt-status-codes:
    - 401
    - 403
```
