### ISSUE TITLE
Categorize containers in separate widgets

### ISSUE THREAD

**Issue by shareef945** [glanceapp/glance#336]
### Description

Feature Request: Filter Docker Containers Widget by Labels

Description
I self-host various applications, some for clients and some for internal use. I'd like to be able to create separate dashboard sections that show only relevant containers based on their labels, allowing me to have different views for internal team members versus external clients.

Use Case
I'm using Glance as a dashboard for both internal team members and external clients. Currently, all docker containers appear in a single widget, which means:
- The dashboard becomes cluttered with irrelevant containers for different user groups
- Can't create separate, clean views for different audiences

Proposed Solution:
- Allow user to rename widgets

This would allow:
- Clean separation of internal and client-facing containers
- Better organization of the dashboard
- More control over what different users can see
- Ability to create purpose-specific sections

Current Workaround
Currently, there is no way to filter containers - all containers appear in a single widget regardless of their labels.

![Image](https://github.com/user-attachments/assets/1603a416-cd2d-4935-a88e-c3af480dbed4)

**Comment by svilenmarkov** [comment]
Hey, if I understand correctly, you want to be able to categorize containers in separate widgets, something along the lines of this:

`glance.yml`

```yaml
- type: docker-containers
  title: Internal containers
  category: internal 

- type: docker-containers
  title: External containers
  category: external
```

`docker-compose.yml`

```yaml
services:
  some-internal-service:
    labels:
      glance.category: internal

  some-external-service:
    labels:
      glance.category: external
```

Where the category can be anything, and if the widget has a category specified it will only show the containers with that category. Is that correct?
