### ISSUE TITLE
`check-url` on Monitor widget does not support favicon file path checking

### ISSUE THREAD

**Issue by 2q2code** [glanceapp/glance#342]
### Description

I run Authelia, and in lieu of providing another kind of authorised checking feature, I figured that the only way to have holistic end-to-end site availability checking that did not compromise security was to add a rule to Authelia to allow the fetching of all site favicons. Here is the rule I added (and tested using wget/curl):
```yaml
    # bypass fetching the favicon to allow site health checking #
      - domain:
          - '*.example.com'
        methods:
          - 'GET'
        resources:
          - '^/favicon.*$'
        policy: 'bypass'
```
I then adjusted my check-url attribute to be something like: `https://somesite.example.com/favicon.ico'

In my head, this should have worked. Authelia shows the path being accessed and permission is not rebuked. Instead the status on the monitored item remains "unauthorised". 🤷‍♀
