### ISSUE TITLE
search widget autofocus does not work on Firefox

### ISSUE THREAD

**Issue by wycre** [glanceapp/glance#348]
### Description

When I have a search widget set up like this:
```yaml
- type: search
          search-engine: duckduckgo
          autofocus: true
```
It does not autofocus the search bar only on Firefox, the autofocus attribute does correctly appear on the element however.

I think this has something to do with Firefox not respecting the autofocus attribute when the element is not present on the original page load. Since the search bar appears a short time after the DOM first loads, Firefox ignores it.

I was able to solve this for myself by adding the following widget below the search widget:
```yaml
- type: html
          source: |
            <script>document.getElementsByClassName('search-input')[0].focus();</script>
``` 

At the very least this quirk should be mentioned in the documentation so others don't have to look far for a solution.
