### ISSUE TITLE
search widget autofocus works irregularly

### ISSUE THREAD

**Issue by Cyantox** [glanceapp/glance#350]
### Description
If I add the search widget to the standard home page to the column in the middle to the top, it only autofocuses it very irregularly. 

```   
   - size: full
      widgets:
        - type: search
          autofocus: true

        - type: group
          widgets:
            - type: hacker-news
            - type: lobsters
```
(cutout)

### Info
It always works at the preconfigured startpage (provided by you in /docs/preconfigured-pages.md), but not at the standard home page. If I press F5 it often works, but not always. For me, it doesn't work about every 4th to 5th time reloading it.
I copied it from the preconfigured startpage 1 to 1 and simply pasted it above the "type: group", so that it is the topmost one in the middle column. (When it then fucusses it, it also works as desired).

The problem occurs in Firefox, Brave & Android Vivaldi Browser - glance is running as docker-compose.
It can also be recognized by the fact that the frame around the search field does not light up.
(This is my first bug report ever, please bear with me)
