### ISSUE TITLE
custom-api parameters

### ISSUE THREAD

**Issue by ralphocdol** [glanceapp/glance#356]
### Description

Hi, thanks for the project. 

I'd like to suggest adding `parameters: ` like the one from `extensions` mainly to make it clean and easier to make a custom-api. Some parameters can be long

from:
```yaml
- type: custom-api
  css-class: services-custom-api
  cache: 1m
  url: ${URL}/api?sample1=test1&sample2=test2&sample3=test3&sample4=test4&sample5=test5
  headers:
    Authorization: Token ${KEY}
    Accept: application/json
  template: |
    <div>some template</div>
```

to:
```yaml
- type: custom-api
  css-class: services-custom-api
  cache: 1m
  url: ${URL}/api
  parameters:
    sample1: test1
    sample2: test2
    sample3: test3
    sample4: test4
    sample5: test5
  headers:
    Authorization: Token ${KEY}
    Accept: application/json
  template: |
    <div>some template</div>
```
