### ISSUE TITLE
array parameters

### ISSUE THREAD

**Issue by ralphocdol** [glanceapp/glance#376]
### Description

After the request for custom-api parameters https://github.com/glanceapp/glance/issues/356, I ended up making an API that needs array parameters to fetch the disk usage of each VMs.
```yml
url: ${WEBSERVER_URL}/api/get-drive-stats?host=test1.local:22&host=test2.local:22&host=test3.local:22&row=2
```

I tested the `extension` which has the parameters if it supports array parameters, but it appears to not support it.

Will it be possible to have this?
```yml
parameters:
   host:
     - test1.local:22
     - test2.local:22
     - test3.local:22
```

![img](https://github.com/ralphocdol/glance-custom-widgets/blob/main/screenshots/drive-stats-2-rows.png?raw=true)
