### ISSUE TITLE
FAQ widget

### ISSUE THREAD

**Issue by vishalkadam47** [glanceapp/glance#377]
### Description

can we have FAQ widget, would be useful
```yml
      widgets:
        - type: faq
          faqs:
            - question: "What is Glance?"
              answer: "Glance is a dashboard application for monitoring various services."
            - question: "How do I install Glance?"
              answer: "You can install Glance using Docker or by downloading the binary."
```

![Image](https://github.com/user-attachments/assets/c55327a5-f6b1-4289-a41c-b08b3903354b)
