### ISSUE TITLE
Timer or Stopwatch widget

### ISSUE THREAD

**Issue by gugugiyu** [glanceapp/glance#381]
### Description

I know there already is a `clock` widget, but the only downside of it is that I'm only being to view the timezone of cities right now, it would be nice if this widget could be further integrated with a timer or a stopwatch.

The timer can either a standalone widget, like `stopwatch` or `timer`, with the following configuration: 

```yml
- type: timer
  hour-format: 24h
  default-timer:
  - title: Task A
    time: 20m
  - timezone: Task B
    label: 1h
  - timezone: Task C
    label: 1s

- type: stopwatch
  hour-format: 24h
```
