### ISSUE TITLE
Preconfigured Startpage broken; line 1: cannot unmarshal !!seq into glance.config

### ISSUE THREAD

**Issue by nodesocket** [glanceapp/glance#392]
### Description

Using the preconfigured [Startpage](https://github.com/glanceapp/glance/blob/main/docs/preconfigured-pages.md#startpage) yaml:

```yaml
- name: Startpage
  width: slim
  hide-desktop-navigation: true
  center-vertically: true
  columns:
    - size: full
      widgets:
        - type: search
          autofocus: true

        - type: monitor
          cache: 1m
          title: Services
          sites:
            - title: Jellyfin
              url: https://yourdomain.com/
              icon: si:jellyfin
            - title: Gitea
              url: https://yourdomain.com/
              icon: si:gitea
            - title: qBittorrent # only for Linux ISOs, of course
              url: https://yourdomain.com/
              icon: si:qbittorrent
            - title: Immich
              url: https://yourdomain.com/
              icon: si:immich
            - title: AdGuard Home
              url: https://yourdomain.com/
              icon: si:adguard
            - title: Vaultwarden
              url: https://yourdomain.com/
              icon: si:vaultwarden

        - type: bookmarks
          groups:
            - title: General
              links:
                - title: Gmail
                  url: https://mail.google.com/mail/u/0/
                - title: Amazon
                  url: https://www.amazon.com/
                - title: Github
                  url: https://github.com/
            - title: Entertainment
              links:
                - title: YouTube
                  url: https://www.youtube.com/
                - title: Prime Video
                  url: https://www.primevideo.com/
                - title: Disney+
                  url: https://www.disneyplus.com/
            - title: Social
              links:
                - title: Reddit
                  url: https://www.reddit.com/
                - title: Twitter
                  url: https://twitter.com/
                - title: Instagram
                  url: https://www.instagram.com/
```

Errors:

```
2025/03/05 23:34:47 Config has errors: yaml: unmarshal errors:

  line 1: cannot unmarshal !!seq into glance.config
```

Running version [v0.7.3](https://hub.docker.com/layers/glanceapp/glance/v0.7.3/images/sha256-2a39016938bf65ceab5ad1d0f09daafb0e0f1a232dde1fa244853937d04dd45f).
