### ISSUE TITLE
Docker Container Widget Yaml Configuration Override

### ISSUE THREAD

**Issue by PhantomOffKanagawa** [glanceapp/glance#401]
### Description

I appreciate the advantage of configuring docker labels as described in [this issue](https://github.com/glanceapp/glance/issues/138) but I prefer being able to control them in configuration to avoid having to restart a compose every time I want edit a persistent attribute of a container's label. I understand that theoretically it should be a one time thing but I am still much happier to write up a bunch of yaml then have to restart a docker compose once. This would also allow greater control over the layout of the docker-containers widget.

TL;DR: I suggest additional yaml configuration to the `docker-containers` widget that would override the docker labels for a given container. A possible look for this could be similar to homepage's configuration for containers [described here](https://gethomepage.dev/configs/docker/#services)

```yaml
- Emby:
  icon: emby.png
  href: "http://emby.home/"
  description: Media server
  server: my-docker # The docker server that was configured
  container: emby # The name of the container you'd like to connect
```

If I am missing something in configuration and this is already possible please let me know and I happy to provide further information on my request or help developing such an idea though I am new to this repository.
