### ISSUE TITLE
dns-stats widget missing api token with pihole v6

### ISSUE THREAD

**Issue by tismofied** [glanceapp/glance#407]
### Description

I’m running Glance in a Docker container inside an LXC on Proxmox, alongside Pi-hole v6 in another LXC. I’m trying to add the dns-stats widget for Pi-hole, but it fails with a "missing API token" error. Here’s my config:
My docker compose:
```
services:
  glance:
    container_name: glance
    image: glanceapp/glance
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt:/mnt:ro
    ports:
      - 8099:8080
    env_file: .env
    labels:
      glance.name: Glance
      glance.icon: di:glance-light
      glance.url: https://homepage.domain.com
      glance.description: Dashboard for self-hosted services
      glance.id: glance
      glance.hide: false
networks: {}
```

In home.yml:

 ```

- type: dns-stats
   service: pihole
   allow-insecure: true
   url: http://192.168.10.4:8080/admin
   username: ${PIHOLE_USERNAME}
   password: "${PIHOLE_PASSWORD}"
```

1. Environment: PIHOLE_PASSWORD is set in my .env file to my Pi-hole web password (e.g., a complex string like @@password#~**).
2. Glance Version: Using glanceapp/glance:latest (pulled March 2025).
3. Pi-hole Version: v6
4. Error: The widget displays "missing API token" on the dashboard. No YAML parsing errors in Glance logs.

but I keep getting this error 
![image](https://github.com/user-attachments/assets/c076173b-84cc-4194-8c8b-628ec1610880)
