### ISSUE TITLE
Another market data source

### ISSUE THREAD

**Issue by Art3mis0940** [glanceapp/glance#411]
### Description

Hello. Could you add another data source for markets widget such as TradingView. Because Yahoo Finance doesn't have native crypto and has strange symbol names. 

Thank you for your development! It's great!!!

**Comment by bastienboutonnet** [comment]
I second that feature request. I was under the impression that passing `symbol-link:` would do the trick but, unless I'm being stupid, doesn't seem to work as a source replacement.

Here's a snippet of what I tried:
```yaml
        - type: markets
          markets:
            - symbol: XRPEUR
              name: XRP/EUR
              symbol-link: https://www.tradingview.com/chart/?symbol=BITSTAMP%3AXRPEUR
```
