### ISSUE TITLE
display docker containers by group

### ISSUE THREAD

**Issue by Telmo** [glanceapp/glance#416]
### Description

- What problem would this feature solve?

When the number of services running in docker exceeds a threshold is hard to find the containers in the list. By grouping them together by their "group" similar to how homepage groups them using the label `homepage.group` will make the containers easier to identify

- Are there any potential downsides to this feature?

Containers that lack the `glance.group` label would have to be handle

- If applicable, what would the configuration for this feature look like?

the current configuration should be enough, alternatively a yaml "selector" could be used to group containers in the UI or to allow for preferred ordering of the groups:

```
- type: docker-containers
  hide-by-default: false
  group-order:
    - Applications
    - Arr
    - DB Services
```

Are there any existing examples of this feature in other software?

https://github.com/gethomepage/homepage uses `homepage.group` labels to group containers together
