### ISSUE TITLE
Server-stats issue on containerized deployment

### ISSUE THREAD

**Issue by tonineri** [glanceapp/glance#417]
### Description

- glanceapp/glance:v0.7.4 (currently latest) deployed via Portainer Stack (docker-compose). AFAIK, it impacts all versions since the `server-stats` feature was introduced.
- glance.yaml part:
   ```yaml
   - type: server-stats
     servers:
       - type: local
         name: HomeLab
         hide-mountpoints-by-default: true
         mountpoints:
           "/":
             name: root
             hide: false
           "/tmp":
             name: tmp
             hide: false
           "/mnt/nfs":
             name: nas
             hide: false
   ```
- Screenshots of the issue
   ![Image](https://github.com/user-attachments/assets/3850805e-fcd8-4b04-ae2c-181a724beb29)
   ![Image](https://github.com/user-attachments/assets/23dda142-8a1f-49df-8ec2-e3cb5b6c5afa)

- Issue should be specific to any containerized deployment of Glance

---

When Glance is containerized and configured with `type: local`, it identifies the container as its host instead of the actual host machine running the container. This is evident from the OS shown in the screenshot, which is `alpine` (the base image of Glance) rather than the host OS, such as `ubuntu` or similar.

Additionally, the `/mnt/nfs` path is not mounted within the container, resulting in `n/a` for storage in the screenshot. Similarly, if I set CPU/RAM limits on my stack (docker-compose) it would impact the CPU/RAM utilization %.

In a containerized setup, only `type: remote` should be valid. However, the [configuration.md](https://github.com/glanceapp/glance/blob/main/docs/configuration.md#server-stats) file states that to display data from a remote server, the Glance Agent must be running on that server. Unfortunately, the [provided link](https://github.com/glanceapp/agent) to download the agent is invalid.

**Comment by svilenmarkov** [comment]
Hey there, this is a known limitation of server monitoring from within a Docker container. 

> Similarly, if I set CPU/RAM limits on my stack (docker-compose) it would impact the CPU/RAM utilization %.

So long as you don't do this, which most people don't, it should still accurately report the CPU and RAM of the host. As for the disk usage, the workaround there is to mount the mountpoints that you want to see the stats for. If you are security conscious you can mount an empty, read-only directory which _should_ still accurately report the used and total amounts of that mountpoint:

```yaml
volumes:
  - /mnt/nfs/nothinghere:/mnt/nfs:ro
```

Ideally though, yes, you would use something that lives on the host and gathers stats that way, such as an agent. The one linked in the docs is coming soon.

**Comment by tonineri** [comment]
> Hey there, this is a known limitation of server monitoring from within a Docker container.
> 
> > Similarly, if I set CPU/RAM limits on my stack (docker-compose) it would impact the CPU/RAM utilization %.
> 
> So long as you don't do this, which most people don't, it should still accurately report the CPU and RAM of the host. As for the disk usage, the workaround there is to mount the mountpoints that you want to see the stats for. If you are security conscious you can mount an empty, read-only directory which _should_ still accurately report the used and total amounts of that mountpoint:
> 
> volumes:
>   - /mnt/nfs/nothinghere:/mnt/nfs:ro
> Ideally though, yes, you would use something that lives on the host and gathers stats that way, such as an agent. The one linked in the docs is coming soon.

Hey, thanks for your reply. I understand that this would work and show the % utilization of my NAS. Thought, it would still show the metrics of the container and not the host itself. I guess I only need to be patient for the agent to be released :)

**Comment by lavinir** [comment]
> the workaround there is to mount the mountpoints that you want to see the stats for. If you are security conscious you can mount an empty, read-only directory which _should_ still accurately report the used and total amounts of that mountpoint:

Hi, I have the same issue. Tried mounting the mount point from the host so I can see the relevant disk usage but it still shows up as N/A. I opened a shell on the container to make sure the the mountpoint is there and it is.
This is my config:

```yaml
  - type: server-stats
          servers:
            - type: local
              name: MyMachine
              hide-mountpoints-by-default: true
              mountpoints:
                "/mnt/glance":
                  hide: false
```
