### ISSUE TITLE
Add RSS property for width

### ISSUE THREAD

**Issue by glenlivet99** [glanceapp/glance#421]
### Description

I would like to grab the image for the verse of the day and display it on Glance. I've set it up so but no matter what style I choose or whether I place the feed in a small or full column, the image is always very small width. I'd like for it to display full size when in a full column so the image is readable. 

```
- type: rss
  title: Verse of the day
  style: horizontal-cards
  limit: 1
  feeds:
    - url: https://feeds.feedburner.com/hl-devos-votd
```
