### ISSUE TITLE
Config has errors: yaml: unmarshal errors:

### ISSUE THREAD

**Issue by bugacha** [glanceapp/glance#424]
### Description

I'm trying to run basic docker compose image with "Preview example configuration file" from https://github.com/glanceapp/glance?tab=readme-ov-file#configuration section

Web page doesnt load

Docker log file errors out with : 

```
glance  | 2025/03/14 19:29:48 Config has errors: yaml: unmarshal errors:
glance  |   line 12: cannot unmarshal !!map into []glance.page
```

**Comment by bugacha** [comment]
Here is a full config that I just copy-pasted from "Preview example configuration file" 

```
pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: calendar
            first-day-of-week: monday

          - type: rss
            limit: 10
            collapse-after: 3
            cache: 12h
            feeds:
              - url: https://selfh.st/rss/
                title: selfh.st
                limit: 4
              - url: https://ciechanow.ski/atom.xml
              - url: https://www.joshwcomeau.com/rss.xml
                title: Josh Comeau
              - url: https://samwho.dev/rss.xml
              - url: https://ishadeed.com/feed.xml
                title: Ahmad Shadeed

          - type: twitch-channels
            channels:
              - theprimeagen
              - j_blow
              - piratesoftware
              - cohhcarnage
              - christitustech
              - EJ_SA

      - size: full
        widgets:
          - type: group
            widgets:
              - type: hacker-news
              - type: lobsters

          - type: videos
            channels:
              - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
              - UCsBjURrPoezykLs9EqgamOA # Fireship
              - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
              - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium

          - type: group
            widgets:
              - type: reddit
                subreddit: technology
                show-thumbnails: true
              - type: reddit
                subreddit: selfhosted
                show-thumbnails: true

      - size: small
        widgets:
          - type: weather
            location: London, United Kingdom
            units: metric
            hour-format: 12h

          - type: markets
            markets:
              - symbol: SPY
                name: S&P 500
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: NVDA
                name: NVIDIA
              - symbol: AAPL
                name: Apple
              - symbol: MSFT
                name: Microsoft

          - type: releases
            cache: 1d
            repositories:
              - glanceapp/glance
              - go-gitea/gitea
              - immich-app/immich
              - syncthing/syncthing
```

**Comment by svilenmarkov** [comment]
I used the config from the readme, as well as the config you provided here in order to try and replicate the issue but both worked fine. Could you try directly downloading an example config?

```
wget https://raw.githubusercontent.com/glanceapp/glance/refs/heads/main/docs/glance.yml
```

**Comment by bugacha** [comment]
> I used the config from the readme, as well as the config you provided here in order to try and replicate the issue but both worked fine. Could you try directly downloading an example config?
> 
> ```
> wget https://raw.githubusercontent.com/glanceapp/glance/refs/heads/main/docs/glance.yml
> ```


I think the problem is in "Docker compose using provided directory structure (recommended)"

`glance.yml` from below doesnt work

```
mkdir glance && cd glance && curl -sL https://github.com/glanceapp/docker-compose-template/archive/refs/heads/main.tar.gz | tar -xzf - --strip-components 2
```

Its content :

```
server:
  assets-path: /app/assets

theme:
  # Note: assets are cached by the browser, changes to the CSS file
  # will not be reflected until the browser cache is cleared (Ctrl+F5)
  custom-css-file: /assets/user.css

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  !include: home.yml
```


If you then replace `home.yml` with content of `Preview example configuration file` - you will get same error that I get

For some reason this `!include: home.yml` doesnt work

**Comment by svilenmarkov** [comment]
> If you then replace home.yml with content of Preview example configuration file - you will get same error that I get

Right, okay. 

There is only one top level `pages` property, which is already present in the `glance.yml` file from the provided directory structure. The `Preview example configuration file` is an example of the entire config file, which also includes that `pages` property, so when you include that, the resulting source looks like this:

```yaml
pages:
  pages:
    - name Home
``` 

When it should look like this:

```yaml
pages:
  - name Home
```

Copying the example file from the readme was not necessary because it is practically identical with the already included `home.yml` from the docker compose template.

In other words, to fix this, remove the `pages:` at the top of your included file.
