### ISSUE TITLE
Video in vertical not opening in new window

### ISSUE THREAD

**Issue by aliaghil** [glanceapp/glance#444]
### Description

Hi Glance Team,

I'm writing to let you know about a small issue I've noticed with the video widget on your platform.

When viewing content in vertical mode, videos from YouTube don't seem to open in a new window as expected. They instead play within the same Glance interface.

However, when viewing in horizontal mode, YouTube videos open correctly in a new window.

I am bringing this to your attention so you can investigate it further. 

All the best
Alex

**Comment by svilenmarkov** [comment]
Hey, I'm not entirely sure what you mean by "vertical mode" and "horizontal mode". Is this referring to the different styles for the videos widget? Could you possibly provide an example config file where the behavior is as expected and where it's doing something you think it shouldn't?

**Comment by aliaghil** [comment]
Hi, and thank you for your quick response.

Yes, I mean the style.

Here is an example of my yml file for the video:

```yml

        - type: group
          widgets:
          # YouTube
            - type: videos
              title: Home Lab
              style: vertical-list
              collapse-after: 5
              channels:
                - UCrVLgIniVg6jW38uVqDRIiQ # Everything Smart Home
                - UCVtQ4AOSmCFUuvixddYiSxw # Smart Home Junkie
            - type: videos
              title: Smart Home
              style: vertical-list
              collapse-after: 5
              channels:
                - UC67SMH0qLMJ4b4Guud0mKjw # Home Automation Guy
                - UCwOBG77Tm8cE24FPxHb_abw # Smart Home Solver

```

Let me know if you need more details.
