### ISSUE TITLE
Config error when adding top-level server directory

### ISSUE THREAD

**Issue by bartolomej** [glanceapp/glance#448]
### Description

I followed [the docs](https://github.com/glanceapp/glance/blob/main/docs/configuration.md#server) and added a top-level server config directory to change the port:

```yml
- name: Software & Startups
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

        - type: rss
          limit: 10
          collapse-after: 3
          cache: 12h
          feeds:
            - url: https://selfh.st/rss/
            - url: https://threedots.tech/index.xml
            - url: https://samwho.dev/rss.xml
            - url: https://faultlore.com/blah/rss.xml
            - url: https://benhoyt.com/writings/rss.xml

    - size: full
      widgets:
        - type: group
          widgets:
            - type: hacker-news
            - type: lobsters

        - type: videos
          channels:
            - UClcE-kVhqyiHCcjYwcpfj9w # LiveOverflow
            - UCaSCt8s_4nfkRglWCvNSDrg # CodeAesthetic
            - UCW6MNdOsqv2E9AjQkv9we7A # PwdFunction
            - UCwd5VFu4KoJNjkWJZMFJGHQ # JacobSorber
            - UCaSCt8s_4nfkRglWCvNSDrg # CodeAesthetic

        - type: group
          widgets:
            - type: reddit
              subreddit: SomebodyMakeThis
              show-thumbnails: true
            - type: reddit
              subreddit: SideProject
              show-thumbnails: true

    - size: small
      widgets:
        - type: weather
          location: Ljubljana, Slovenia
          units: metric
          hour-format: 24h

        - type: markets
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: BTC-USD
              name: Bitcoin
            - symbol: ETH-USD
              name: Ethereum

        - type: releases
          cache: 1d
          # Without authentication the Github API allows for up to 60 requests per hour. You can create a
          # read-only token from your Github account settings and use it here to increase the limit.
          # token: ...
          repositories:
            - modelcontextprotocol/specification
            - modelcontextprotocol/servers

server:
  port: 6969
  assets-path: /app/assets

```

... but when running the server, I get the error:

```bash
➜  glance git:(main) ✗ docker compose up
[+] Running 1/0
 ⠿ Container glance  Created                                                                                                    0.0s
Attaching to glance
glance  | 2025/03/16 18:29:24 Config has errors: yaml: line 11: did not find expected '-' indicator
glance exited with code 0
```

Am I missing something here? I expect this to work. When I remove the server config, everything works.

**Comment by bartolomej** [comment]
I think this probably happened because I should have nested my pages config under "pages" key as that's done in the example config here: https://github.com/glanceapp/glance/blob/main/docs/glance.yml. If that's the case, I think it should be nested like that by default, so that it doesn't lead to possible confusion like in my case.

But even when I did that, I still ran into some config parsing issues. This is what I got after using the example config I listed above:

```bash
➜  glance git:(main) ✗ docker compose up
[+] Running 1/0
 ⠿ Container glance  Created                                                                                                    0.0s
Attaching to glance
glance  | 2025/03/16 18:58:00 Config has errors: yaml: unmarshal errors:
glance  |   line 12: cannot unmarshal !!map into []glance.page
glance exited with code 0
```

**Comment by svilenmarkov** [comment]
Hey, I think what's happened is you've added the `server` property within the `home.yml` file and not the `glance.yml` file. YAML itself does not support including files, so the way Glance does it is by taking the contents of the included file and just inserting them where the `!include` directive is, then handing all of that to be parsed by the YAML parser as a single file. This means that all of the config files are just one big file, so "top level" refers the top level of the first included file, which by default is `glance.yml`.

**Comment by Elsenosy** [comment]
Hi there, I think the issue is with the identation of  the server directive 

![Image](https://github.com/user-attachments/assets/007974b4-a2c3-44b6-88e8-d3dd0b345fae)

Could you fix the indentation? It will work fine. 

Here is the fixed yml file
```yml
- name: Software & Startups
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

        - type: rss
          limit: 10
          collapse-after: 3
          cache: 12h
          feeds:
            - url: https://selfh.st/rss/
            - url: https://threedots.tech/index.xml
            - url: https://samwho.dev/rss.xml
            - url: https://faultlore.com/blah/rss.xml
            - url: https://benhoyt.com/writings/rss.xml

    - size: full
      widgets:
        - type: group
          widgets:
            - type: hacker-news
            - type: lobsters

        - type: videos
          channels:
            - UClcE-kVhqyiHCcjYwcpfj9w # LiveOverflow
            - UCaSCt8s_4nfkRglWCvNSDrg # CodeAesthetic
            - UCW6MNdOsqv2E9AjQkv9we7A # PwdFunction
            - UCwd5VFu4KoJNjkWJZMFJGHQ # JacobSorber
            - UCaSCt8s_4nfkRglWCvNSDrg # CodeAesthetic

        - type: group
          widgets:
            - type: reddit
              subreddit: SomebodyMakeThis
              show-thumbnails: true
            - type: reddit
              subreddit: SideProject
              show-thumbnails: true

    - size: small
      widgets:
        - type: weather
          location: Ljubljana, Slovenia
          units: metric
          hour-format: 24h

        - type: markets
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: BTC-USD
              name: Bitcoin
            - symbol: ETH-USD
              name: Ethereum

        - type: releases
          cache: 1d
          # Without authentication the Github API allows for up to 60 requests per hour. You can create a
          # read-only token from your Github account settings and use it here to increase the limit.
          # token: ...
          repositories:
            - modelcontextprotocol/specification
            - modelcontextprotocol/servers

  server:
    port: 6969
    assets-path: /app/assets

```
