### ISSUE TITLE
Docker Container YAML Configuration Support

### ISSUE THREAD

**Issue by mike391** [glanceapp/glance#452]
### Description

Instead of using docker labels to configure how containers show up, it would be convenient for a lot of users if we could just use `glance.yml` to configure how containers show up in the `docker-containers` widget.  Some users have many containers and don't want to change all their docker compose files to add labels as it would be time consuming and it might even be a reason they dont give using glance a chance.

The proposed behavior will add a check to see if a container name exists in the `glance.yml` and if it does then use the defined overrides there. If a container is not reverenced in `glance.yml` then the dashboard will continue as usual using docker labels to configure containers. This way users dont have to choose between either configuration option and existing users with labels can take advantage of this as well.  

The proposed `glance.yml` configuration will look like this:

```
          - type: docker-containers
            hide-by-default: false
            containers:
              glance:  # This is the actual container name
                title: "test-glances"
                description: "test-description"
                url: "127.0.0.1:3011/test"
                icon: "si:jellyfin"
```

I will implement this myself.
