### ISSUE TITLE
Certificates monitoring

### ISSUE THREAD

**Issue by slashformotion** [glanceapp/glance#455]
### Description

# I am interested in implementing a widget that allows the user to monitor a domain's certificates.

What problem would this feature solve?
> Glance is likely to become my one stop shop for my dashboarding needs and i currently use a script to monitor my certificates. Adding it to glance would be great.

If applicable, what would the configuration for this feature look like?
```yaml
- type: certificates
  title: My certs
  style: horizontal-cards
  feeds:
    - url: https://myimmich.lan
      title: Immich
    - url: https://prox.lan
      title: proxmox
```

Are there any existing examples of this feature in other software?
> there are many solution to monitor you certificates, the most interesting/customizable ones are geared toward businesses and cost a lot of money.
