### ISSUE TITLE
Ability to Skip TLS Certificate Verification for Custom API Widgets

### ISSUE THREAD

**Issue by mrusso99** [glanceapp/glance#484]
Currently, when using the custom-api widget in Glance, connecting to services that use self-signed certificates or certificates from untrusted authorities causes issues with the following error:

`tls: failed to verify certificate: x509: certificate signed by unknown authority`

There is currently no option in Glance to bypass TLS certificate verification.

The configuration could be added to the custom-api widget YAML definition. An example configuration might look like this:
 
```
- type: custom-api
  title: Example API
  url: https://example.com/api/endpoint
  insecure: true  # Skip TLS certificate verification
  headers:
    Authorization: Bearer <token>
  template: |
    {{ .JSON.String "key" }}
```
