### ISSUE TITLE
Unable to retrive RSS feed from malaysian cert

### ISSUE THREAD

**Issue by le0li9ht** [glanceapp/glance#485]
### Description

I am running glance in ubuntu 24.04 as standalone binary.
I am using the latest version of glance.

![Image](https://github.com/user-attachments/assets/b827cdd9-154e-4389-a885-2275bf06eb1d)

 I am getting following error for rss feed. Rss feed is looking but why its getting banned?
`2025/03/21 15:10:19 ERROR Failed to get RSS feed url=https://www.mycert.org.my/portal/rss error="unexpected status code 403 from https://www.mycert.org.my/portal/rss"`

**Comment by svilenmarkov** [comment]
Hey, could you try adding a fake user agent to the headers like this?

```yaml
feeds: 
  - url: https://www.mycert.org.my/portal/rss
    headers:
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0
```
