### ISSUE TITLE
parameter functions

### ISSUE THREAD

**Issue by ralphocdol** [glanceapp/glance#502]
### Description

Will it be possible for parameters for type `custom-api` or `extension` to have their parameters use some functions from https://github.com/glanceapp/glance/blob/main/docs/custom-api.md#functions.
I remember that there will be more functions coming for `custom-api` type like one that handles the `date`

In the upcoming v0.8, parameters for `custom-api` will be supported, so I was thinking of something like this
```yml
- type: custom-api
  url: https://some-domain.com
  parameters:
     start-date: {{ startOfDay now }}
     end-date: {{ endOfDay now }}
```
resulting query values
```url
start-date=2025-03-24T00:00:00Z
end-date=2025-03-24T23:59:59Z
```
