### ISSUE TITLE
Optional OAuth2 configuration for the Reddit widget

### ISSUE THREAD

**Issue by s0ders** [glanceapp/glance#509]
### Description

It is a known issue that, when self-hosting Glance, Reddit will block network calls to its endpoints. A potential workaround mentionned in the documentation is the use of a proxy but it is not always a feasible or optimal solution.

An other way of working around this issue is, as mention in [this issue](https://github.com/glanceapp/glance/issues/4#issuecomment-2081435366), to [register an app on Reddit ](https://ssl.reddit.com/prefs/apps/) (which takes about two clicks), an use the client ID and secret to have a free and functioning access to the Reddit API (using `oauth.reddit.com` instead of `www.reddit.com`) even from an instance hosted on a VPS.

This would require adding new optional configuration properties to the Reddit widget such as: `app-client-id`, `app-secret`, `app-name`. If these three configurations are found for a Reddit widget configuration, an access token is fetched and `oauth.reddit.com` endpoints are used instead of `www.reddit.com`.

```yaml
# Example configuration for the Reddit widget using client ID and secret
widgets:
  - type: reddit
    subreddit: technology
    show-thumbnails: true
    reddit-app-name: ${REDDIT_APP_NAME} # Values stored in a .env
    reddit-client-id: ${REDDIT_APP_CLIENT_ID}
    reddit-client-secret: ${REDDIT_APP_SECRET}
```

Given that `app-secret` and `app-client-id` are secret values, they can be stored in a `.env` file and populated at runtime.

Implementing this is fairly straightforward and I have already forked the repository to make a [simple implementation of that feature](https://github.com/s0ders/glance/blob/main/internal/glance/widget-reddit.go#L55).

Please let me know if this is something that you considering adding to this project or if it is out of scope.

**Comment by tonylaw7** [comment]
I was scratching my head over this and your open issue was the first result. This looks like a neat solution, hopefully this feature  will get picked up.

**Comment by Nirzak** [comment]
I think you should create a pull request for it. At least I will like to get this feature without using that proxy solution. Thanks a lot man for implementing this

**Comment by s0ders** [comment]
Thanks for your replies. Will submit a PR for this today.

**Comment by SR-G** [comment]
Thanks for the PR, useful.

And I can confirm that the corresponding PR is working fine (i was also encountering these 403 errors, as i deployed glance in a dedicated server (OVH datacenters)).

Just two remarks : 
- the documentation could be a little bit more precise, about creating the reddit app : 
  - "web app" type
  - about URL can be blank + redirect URI has to be filled, but anything can be put (https://glance.mydomain.tld, etc.)
- ideally speaking the configuration in `glance.yaml` should be declared only once for reddit as a whole, and not one time per subreddit (ok, it's duplicated and just 4 lines, but i'm not sure it makes a lot of sense to have this kind of configuration duplicated several times)

**Comment by pgagnidze** [comment]
@SR-G You can use YAML anchors and aliases to avoid duplication:

```yaml
define: &shared-properties
  type: reddit
  app-name: ${REDDIT_APP_NAME}
  client-id: ${REDDIT_APP_CLIENT_ID}
  client-secret: ${REDDIT_APP_SECRET}
  comments-url-template: https://redlib.fly.dev/{POST-PATH}
```

Each subreddit widget references this with `<<: *shared-properties`, so OAuth credentials are declared once and shared across all subreddit widgets. You can see a full example https://github.com/Owloops/flyo/blob/main/apps/glance/glance.yml.template#L51-L56
