### ISSUE TITLE
DOCKER_HOST is not considered when making requests to docker

### ISSUE THREAD

**Issue by progress44** [glanceapp/glance#510]
### Description

How did you install Glance? (Docker container, manual binary install, etc)
Docker container

Which version of Glance are you using?
0.7.7

Include the relevant parts of your glance.yml if applicable (widget, data source, properties used, etc)

```yml
        - type: docker-containers
          hide-by-default: false
```

Include any relevant logs or screenshots if applicable
<img width="1601" alt="Image" src="https://github.com/user-attachments/assets/18c4cc6e-7868-4677-a5d4-efecb59fd1dc" />

Is the issue specific to a certain browser or OS?
No

Steps to reliably reproduce the issue

docker-compose.yml
```yml
networks:
  edge:
  internal:
  socket:

services:
  glance:
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ${CONFIGS_DIR}/glance/config:/app/config
      - ${CONFIGS_DIR}/glance/assets:/app/assets
    networks:
      - edge
      - local
      - socket
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glance.rule=Host(`glance.${DNS}`)"
      - "traefik.http.routers.glance.entrypoints=websecure"
      - "traefik.http.routers.glance.middlewares=cf-external"
      - "traefik.http.routers.glance.service=glance"
      - "traefik.http.services.glance.loadbalancer.server.port=8080"

      - glance.name=Glance
      - glance.icon=https://www.glanceapp.io/assets/glance-logo.svg
      - glance.url=https://glance.${DNS}
      - glance.description=Glance
      - glance.id=glance
      - glance.parent=Dashboard
    environment:
      - DNS=${DNS}
      - DOCKER_HOST=tcp://dockersocket:2375

  dockersocket:
    container_name: ${COMPOSE_PROJECT_NAME}.dockersocket
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - socket
    environment:
      - LOG_LEVEL=info
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1 # Watchtower
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik, portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1 # Portainer
      - INFO=1 # Portainer
      - NETWORKS=1 # Portainer
      - NODES=0
      - PLUGINS=0
      - SERVICES=1 # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1 # Portainer
      - VOLUMES=1 # Portainer
    privileged: true
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 -q -O /dev/stdout http://localhost:2375/version || exit 1
      interval: 10s
      retries: 12
      start_period: 10s
      timeout: 10s
```

Are you hosting Glance on a VPS?
Homelab

Anything else you think might be relevant
I think the request should not be made to `http://docker` but should consider the $DOCKER_HOST env variable.
