### ISSUE TITLE
Enhance the currency display precision settings within the markets component.

### ISSUE THREAD

**Issue by nsdont** [glanceapp/glance#515]
### Description

# Background 

When using the markets component to show specific exchange rates, particularly for low-value currencies like the Japanese Yen (like JPYUSD=X), the current way of rounding off the numbers isn't quite right. For instance, the exchange rate between the Yen and the US Dollar is often very low (like 0.0066). When you round it, it might show up as 0.01 or even 0, which is a big difference from what the real rate is.

Current configuration is as follows:
```yaml
- type: markets
  markets:
    - symbol: JPYUSD=X
      name: JPY-USD
```
But the numbers shown have been rounded, which can make the exchange rate info seem a bit off.

Take a look at the image below, for instance.

<img width="403" alt="Image" src="https://github.com/user-attachments/assets/17cba90a-4b14-4825-9d59-73db18132c48" />

<img width="327" alt="Image" src="https://github.com/user-attachments/assets/78596588-d6fc-416b-8b26-02e0cb7a7864" />

# Expected Behavior

We would like to introduce one of the following options, or any other improved display controls:
1. Precision Control Option: Enable users to specify the number of decimal places for certain currencies

```yaml
- symbol: JPYUSD=X
    name: JPY-USD
    precision: 4 # Show values with 4 decimal places
```

2. Scaling Factor Option: For currencies with low values, allow adjusting the display with a scaling factor
```yaml
- symbol: JPYUSD=X
    name: JPY-USD
    scale: 100 # Multiply the value by 100 for display
```
