### ISSUE TITLE
Widget Monitor health check logic

### ISSUE THREAD

**Issue by zJiaJun** [glanceapp/glance#522]
### Description

My Glance is deployed in the NAS container environment. The monitor configuration is as follows.

```
- type: monitor
          cache: 1m
          title: Services
          sites:
            - title: Asus Router
              url: http://192.168.50.1
              icon: di:asus-router
            - title: QNAP
              url: http://192.168.50.167:5000
              icon: di:qnap
            - title: qBittorrent
              url: http://192.168.50.167:8090
              check-url: http://192.168.50.167:5000
              icon: di:qbittorrent
            - title: File Browser
              url: http://192.168.50.167:8600
              icon: di:filebrowser
              check-url: http://192.168.50.167:5000
            - title: Gogs
              url: http://192.168.50.167:10088
              icon: di:git
            - title: Prometheus
              url: http://192.168.50.167:9090
              icon: di:prometheus
            - title: Grafana
              url: http://192.168.50.167:3000
              icon: di:grafana
            - title: Jellyfin
              url: http://192.168.50.167:8096
              icon: di:jellyfin
            - title: Portainer
              url: http://192.168.50.167:9000
              icon: di:portainer
            - title: Stash
              url: http://192.168.50.167:9999
              icon: di:stash
            - title: Immich
              url: http://192.168.50.167:2283
              icon: di:immich
```

<img width="1252" alt="Image" src="https://github.com/user-attachments/assets/bd9d89fd-22df-499e-af6a-44fcd5a4a31b" />

The titles are "Asus Router" and "QNAP". The health check can pass for them, but for other URLs, it fails. When I configure the check URL (the URL of QNAP) for other sites, the health check can pass.

I'm sure that all the services of the site have been started normally.

What is the cause of this problem? Please let me know.
