### ISSUE TITLE
Search widget RAW_QUERY parameter

### ISSUE THREAD

**Issue by Re4GD** [glanceapp/glance#527]
### Description

Current search widget configuration:
``` 
- type: search
  search-engine: duckduckgo
  new-tab: true
  bangs:
    - title: Github Repository
      shortcut: "!ghr"
      url: https://github.com/{RAW_QUERY}
```

I need the ability to use the raw query parameter without the URL encoding

Currently:
`!ghr glanceapp/glance` -> `https://github.com/glanceapp%2Fglance`

With raw query param
`!ghr glanceapp/glance` -> `https://github.com/glanceapp/glance`
