### ISSUE TITLE
for widgets calendar and clock please make user can choose format

### ISSUE THREAD

**Issue by Paul-16098** [glanceapp/glance#541]
### Description

lib of this feature:
https://github.com/iamkun/dayjs

the configuration for this feature look like?
```yml
          - type: calendar
            first-day-of-week: sunday
            format: YYYY-MM-DD
```

![Image](https://github.com/user-attachments/assets/08266fab-b8fd-466b-939c-631f5baa14b9)
