### ISSUE TITLE
Feature request: Auto switch dark/light mode themes based on OS

### ISSUE THREAD

**Issue by nickian** [glanceapp/glance#55]
It would be nice to be able to set two themes, one for the OS light mode and one of OS dark mode and autoswitch based on OS state. Something like:

```yml
theme-dark:
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76

theme-light:
  background-color: 0 0 95
  primary-color: 0 0 10
  negative-color: 0 90 50
```

Using CSS like this:

```css
@media (prefers-color-scheme: dark) {
    ...
}
```

**Comment by svilenmarkov** [comment]
Hey, thanks for the idea!

I've actually been thinking about adding the ability to set theme presets and then being able to switch between them from the UI so you don't have to annoyingly restart Glance to change your theme. I don't have an ETA for that yet but whenever it does get implemented I'll be able to also add the ability to switch the scheme automatically based on OS preference.

**Comment by nickian** [comment]
I decided to create a different solution for the time being. If anyone else is interested, it's here now:

https://github.com/nickian/Glance-Theme-Switch

**Comment by ShivamJoker** [comment]
@svilenmarkov can I work on this?

**Comment by ffflick-gh** [comment]
I rely on switching between light/dark OS themes quite often, so this would be a very helpful feature!

**Comment by alinnert** [comment]
If I may make another suggestion: I'd like it if the theme config properties are raw CSS color values. If the global CSS contained this:

``` css
:root {
  color-scheme: light dark;
}
```

then the config could look like this:

``` yaml
theme:
  background-color: light-dark(hsl(220 23 95), hsl(229 19 23))
  primary-color: light-dark(hsl(220 91 54), hsl(222 74 74))
  positive-color: light-dark(hsl(109 58 40), hsl(96 44 68))
  negative-color: light-dark(hsl(347 87 44), hsl(359 68 71))
  contrast-multiplier: 1.2
```

And also other color notations can be used like hex values or oklch.
