### ISSUE TITLE
please support display base64-image

### ISSUE THREAD

**Issue by atliuhui** [glanceapp/glance#582]
### Description

When the media of the feed is base64-image, the image cannot be displayed.

# feed
```xml
<?xml version="1.0" encoding="utf-8"?>
<feed xml:lang="zh-CN" xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/">
  <entry>
    <id>1</id>
    <title>title1</title>
    <updated>2025-01-01</updated>
    <summary>summary</summary>
    <category label="2025" />
    <category label="Other" />
    <media:thumbnail url="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAQkSURBVGhD7ZrfK2VRFMfXTCaNB0Q8IPL7SY1MUQjNg5Bf8eaJmImHMQ8U/4ASmuaFrpnhQV4UoZgHNImkhInyc5BbwosozeTnzP6evczl+Hn2ubr3Tj61umstp2t/23uvc87a9xnpCA4OfiU+3gp7IyxU2AthzsCJsA1hI8JarVbrDyQv+CdECHgpPj4Kg4hrAp2MP8I+C/sgBP1GQhswi/gmLAWxCzEqLANinstYmwlXEwEw5k9wnvGemIGPhAuCZfYaM+IKe+IuMPZ3mJFl4URpKTsRHR1NMTEx5OXlRd7e3nR4eEj7+/u0uLhIc3NzfJVdWYWQY+GYLrHu7u5UVlZGJSUl5Ovry9nrHBwcUEdHB7W2tmq+nTiBEKwxU8THx1NjYyOqH2fuZ29vj6qqqmhkBLcF81xULWXS0tKoq6vLkAjg4+NDbW1tlJeXxxlzmJqR0NBQ6uvr0/aCnvHxcVpbW9MsMDCQIiIiKCkpSVuCevLz82lmBoVTHVNC6urqqKioiCPJ0NCQtsyWlpY4YyMgIIBqa2spJyeHM5LBwUEqLy/nSA1lIf7+/jQ1NcWRBHFhYSFHt9Pc3ExZWVkcSTIyMmhhYYEj4yjvkdTUVPZs1NfXs3c3TU1N7NlISTH3YKEsJCEhgT3JxsbGtRm6Deyb6elpjiSJiYnsqaEsRL/BMTgjbG1tsScJCwtjTw1lIbhjX8aoENzhu7u7qaenR6t8s7Oz/Bc1lDc7BhAXF8cRkcVi0aqYozB9Q3QWnoQ4G09CnI1HrVp47PDw8ODoflCOVXlUIS0tLZSZmcnR/YSEhLBnHKdZWqenp+yp4TRCTk7QSFTnUYVsb2/T8PDwjba5uclXScwKcdgjSk1NzZWXKbzDx8bGcmScp6VlluNjdKFs/DdCzs7O2FNDWcj5+Tl7Ejc3N/Yehn7g+u8zirIQfZfQ6BteeHg4exK0VM2gLET/j/UDuw+9cIcJmZycZE8iyviDGwiRkZFXSjeYmJhgTw1lIWNjY+zZqK6uZu9uKisr2bMxOorDJ3WUhezs7FBnZydHEtzQ2tvbKSrq5lMK9HsbGhooOzubM5L+/n5aXsbphjrKd3YQFBREvb295OfnxxkbeAxZXV2l9fV1rfeL5ZScnEyenp58heTo6IgKCgpofn6eM2qYEgLQmNbPjBEqKipoYGCAI3WUl9YF6Lrn5ubSysoKZx4GliYa4PYQAUzPyGVKS0upuLhYW3K3sbu7++/ECsvKXkCIXY7eLoNSfNMZIo4ajM7cA9GO3ux+GOoAfmKPfJe+S/MdQizC7LZPHADGbnlutVrRBv+ipVyTNqFh+qL8fhA2Ll2XAmN+D0cTIhT9Eh/pwr4Kc4VlhjFirOk89uu/QRFVDI+l74SlCUPHzJl+eIbWC4qTBcsJSQnRX7qrhcZrycA0AAAAAElFTkSuQmCC" medium="image" />
  </entry>
</feed>
```
# glance.yml
```yml
  - name: Debugging
    columns:
      - size: full
        widgets:
          - type: rss
            show-thumbnails: true
            style: detailed-list
            feeds:
              - url: http://localhost/feeds/sample.xml
                title: debug
```
