### ISSUE TITLE
DeArrow setting for the YT videos widget

### ISSUE THREAD

**Issue by ynn-dev** [glanceapp/glance#592]
### Description

Hi everyone,
I propose the addition of [DeArrow](https://dearrow.ajay.app/) support for the Youtube videos widget. DeArrow is a crowd-sourced database of improved YT videos titles and thumbnails to make them better and clickbait-y.
I already implemented the title swap, and I now need to add the thumbnail swap.
I was thinking of adding two new options to the video:
```YAML
- type: videos
  channels:
    - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
    - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
    - UCsBjURrPoezykLs9EqgamOA # Fireship
    - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
    - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium
  use-dearrow-title: true
  use-dearrow-thumbnail: false
```
The DeArrow API is very simple and you can find the documentation [here](https://wiki.sponsor.ajay.app/w/API_Docs/DeArrow).

Here is a comparison of before vs after with just the title swap:
![Image](https://github.com/user-attachments/assets/c7dbcb30-108f-425e-9322-758f40bbd11c)
![Image](https://github.com/user-attachments/assets/9725e80f-ca08-4323-a365-be21b5bec008)
