### ISSUE TITLE
Weather lookup does not find some locations

### ISSUE THREAD

**Issue by MooToYou** [glanceapp/glance#615]
### Description

Using Glance from git, main branch commit `44fca910`

Running locally on Windows with `go run .`

My glance.yml for testing:

```yaml
pages:
  - name: Home
    columns:
      - size: full
        widgets:
          - type: weather
            location: Lancaster, United Kingdom
            units: metric
            hour-format: 12h
```

For reference, I am trying to look up Lancaster, United Kingdom.

With this Geocoding API url https://open-meteo.com/en/docs/geocoding-api?name=Lancaster&count=10 we get 10 results, all of which are USA. Expanding the results to 20 we see that Lancaster, UK is at position 19 in the list. 

If we add the country code, it now displays zero results: https://open-meteo.com/en/docs/geocoding-api?name=Lancaster&countryCode=GB

However setting the total returned rows to 20, we then get our Lancaster, UK result : https://open-meteo.com/en/docs/geocoding-api?name=Lancaster&countryCode=GB&count=20

I suspect this is more to do with how the Geocoding API handles results internally before returning the JSON, such as applying the count before the country code so we would have 20 results for Lancaster, reduced to 10 and then filtering the top 10 (all of which are USA) for country code GB. Pure speculation, I don't know enough about Swift to be able to dig into their source code to figure that one out (though I will give it a good try!)

I have "fixed" this locally by changing the requestUrl within the function `fetchOpenMeteoPlaceFromName` to count of 20, however I guess a proper fix would be to add extra parameters for count and countryCode? I'd gladly take a look at implementing this if it's a valid fix/feature, have never worked with Go before so could be an interesting starting point
