### ISSUE TITLE
limit modifier strange behavior

### ISSUE THREAD

**Issue by schlegelt1** [glanceapp/glance#627]
### Description

When trying to incorporate an RSS feed into my glance, I want to limit each individual feed source so they don't overwhelm the diversity of the aggregate feed:

```
- type: rss
  title: Crypto News
  collapse-after: 8
  feeds: 
    - url: https://www.coindesk.com/feed
      title: CoinDesk
      limit: 5
    - url: https://www.theblock.co/feed  
      title: The Block
      limit: 5
    - url: https://cointelegraph.com/rss  
      title: Cointelegraph
      limit: 5
    - url: https://www.reddit.com/r/CryptoCurrency.rss
      title: CryptoCurrency Subreddit
      limit: 5
    - url: https://www.reddit.com/r/algorand.rss
      title: Algorand Subreddit
      limit: 5
```

Sometimes it works perfectly, other times it limits the entire rss feed to just 5 cards. It's hit or miss.

**Comment by svilenmarkov** [comment]
Only reason I can think of that it would do this is if it fails to fetch some of those feeds, are there any errors in the console?

**Comment by schlegelt1** [comment]
You're right, there was an error in one of the feeds (the block) and it stopped any following feed from loading. I've removed it and regained the desired function.

**Comment by svilenmarkov** [comment]
That shouldn't be the case, if any of the feeds fail then the rest should still load. I tried using the config you provided and that was the behavior I saw. Are there any other properties you've used as well?

**Comment by schlegelt1** [comment]
I had cache: 5m at one point, and limit 20 at the widget level. 

```
- type: rss
  title: Crypto News
  cache: 5m
  limit: 20
  collapse-after: 8
  feeds: 
    - url: https://www.coindesk.com/feed
      title: CoinDesk
      limit: 5
    - url: https://www.theblock.co/feed  
      title: The Block
      limit: 5
    - url: https://cointelegraph.com/rss  
      title: Cointelegraph
      limit: 5
    - url: https://www.reddit.com/r/CryptoCurrency.rss
      title: CryptoCurrency Subreddit
      limit: 5
    - url: https://www.reddit.com/r/algorand.rss
      title: Algorand Subreddit
      limit: 5
```

To summarize: there was an error in theblock feed, and Cointelegraph was the only feed displaying at all with no colklapse-after pull down.
