### ISSUE TITLE
Pages Center Vertically not applying

### ISSUE THREAD

**Issue by LZStealth** [glanceapp/glance#654]
### Description

The vertical alignment of pages no longer appears to be working since update v8.0
The CSS looks to be applying this to .page.center-vertically however the class is page-center-vertically

Not sure if this is affecting other items with the .page.<property>

**Comment by svilenmarkov** [comment]
Thanks for reporting this, I'll release a fix for it in the next few days. As a temporary quick fix, you can add the following custom CSS:

```css
.page.page-center-vertically {
    display: flex;
    justify-content: center;
    flex-direction: column;
}
```
