### ISSUE TITLE
Panic: nil pointer dereference when using releases widget in head-widgets (v0.8.0, Docker)

### ISSUE THREAD

**Issue by aykhans** [glanceapp/glance#660]
### Description

First of all, thank you for this excellent project!

I'm using Glance via Docker, version v0.8.0.

When I try to use the `releases` widget inside the `head-widgets` section, I encounter a runtime panic with the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x91b07d]

goroutine 28 [running]:
github.com/glanceapp/glance/internal/glance.(*releasesWidget).update(0xc0002291e0, {0x0?, 0x0?})
        /home/runner/work/glance/glance/internal/glance/widget-releases.go:67 +0xfd
github.com/glanceapp/glance/internal/glance.(*page).updateOutdatedWidgets.func1()
        /home/runner/work/glance/glance/internal/glance/glance.go:242 +0x54
created by github.com/glanceapp/glance/internal/glance.(*page).updateOutdatedWidgets in goroutine 26
        /home/runner/work/glance/glance/internal/glance/glance.go:240 +0x165
```

**Steps to reproduce:**
I believe the issue can be reliably reproduced by using the following configuration files:

`glance.yml`:
```
server:
    assets-path: /app/assets

auth:
  secret-key: ${SECRET_KEY}
  users:
    admin:
      password: ${ADMIN_PASSWORD}

theme:
    background-color: 240 13 14
    primary-color: 51 33 68
    negative-color: 358 100 68
    contrast-multiplier: 1.2

pages:
    $include: home.yml
```

`home.yml`:
```
- name: Home
  head-widgets:
    - type: releases
      cache: 6h
      token: ${GITHUB_TOKEN}
      repositories:
          - glanceapp/glance

  columns:
      - size: full
```
