### ISSUE TITLE
Allow better customization of color presets

### ISSUE THREAD

**Issue by EricKotato** [glanceapp/glance#665]
### Description

Currently presets can change only color theme. However, it would be nice to have a CSS customization per theme.

It could be achieved in one of two possible ways:
1. By allowing `custom-css-file` preset option.
2. By adding class with current theme like `theme-default-dark`, `theme-default-light` or however is theme called in presets (with prefix, perhaps?).

This will greatly improve customization without hurting other possible themes.

**Comment by svilenmarkov** [comment]
Thanks for the suggestion, this is now possible in v0.8.3 via:

```css
:root[data-theme="default-dark"] {
    .color-primary-if-not-visited {
        color: #ff0000;
    }
}

:root[data-theme="default-light"] {
    .color-primary-if-not-visited {
        color: #00ff00;
    }
}

:root[data-theme="your-theme-name"] {
    .color-primary-if-not-visited { 
        color: #0000ff;
    }
}
```
