### ISSUE TITLE
On a docker compose install, with a non default port, docker health check always fails

### ISSUE THREAD

**Issue by Nifle-CGE** [glanceapp/glance#676]
### Description

On a docker compose install with this config
```yml
services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: always
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      # Optionally, also mount docker socket if you want to use the docker containers widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # To get storage stats
      - /mnt/pool:/mnt/pool:ro
    network_mode: host
    env_file: .env
```
with this in glance.yml
```yml
server:
  port: 60010
  assets-path: /app/assets

theme:
  # Note: assets are cached by the browser, changes to the CSS file
  # will not be reflected until the browser cache is cleared (Ctrl+F5)
  custom-css-file: /assets/user.css

  # Teal City
  background-color: 225 14 15
  primary-color: 157 47 65
  contrast-multiplier: 1.1

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  !include: home.yml
```
Docker health check always fails (see **unhealthy**) even though glance works perfectly
```
0e257e99b242    glanceapp/glance    "/app/glance    --confi…"    6 hours ago    Up 6 hours (unhealthy)
```
