### ISSUE TITLE
Server Stats Widget always showing 100% CPU load

### ISSUE THREAD

**Issue by JoghurtSommelier** [glanceapp/glance#679]
### Description

I am running glance v0.8.2 inside a docker container on my Synology DS220+ and the CPU load of the Server Stats widget is always showing 100% CPU load. The RAM and Drive usage is correct.

Widget Yaml:
```      
- type: server-stats
  servers:
    - type: local
      name: Services
```

**Comment by svilenmarkov** [comment]
Is the container CPU limited by any chance? Also, do you know what the actual CPU usage hovers at?

**Comment by SoundsGreaat** [comment]
I have the same problem, if at least one processor core is loaded, the widget displays 100%, although all other cores can be completely unloaded

![Image](https://github.com/user-attachments/assets/30cb631e-9eee-4ec9-a9c9-42ce0bcda553)
![Image](https://github.com/user-attachments/assets/30811795-bf24-4b96-82a7-b7c2f4c4f3ed)

docker compose:
```
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ~/docker-dir/${DOCKER_DIR_NAME}/glance:/app/config
      - /mnt/nas:/media
    ports:
      - '8081:8080'
    env_file:
      - .env
    networks:
      - main
```
