### ISSUE TITLE
Add Analog Clock

### ISSUE THREAD

**Issue by anant-j** [glanceapp/glance#690]
### Description

I’ve implemented an Analog Clock widget in Glance as part of my local build and found it quite useful. I’d like to propose contributing this feature to the main repository if you think it could benefit other users as well.

Examples:
![Image](https://github.com/user-attachments/assets/fff9d8c0-29b9-4d01-90ed-14f5ff82752e)
![Image](https://github.com/user-attachments/assets/6ff46f22-be68-40f3-8829-dcada4d0ad1d)

A working version of the code can be found here:
👉 https://github.com/anant-j/glance/tree/AddAnalogClock

Sample config:
```
- type: analog-clock
  hide-am-pm-indicator: false
  hide-date: false
  dial-markers: "NumericalFull"
  timezones:
  - timezone: Europe/Paris
    label: Paris
  - timezone: America/New_York
    label: New York
  - timezone: Asia/Tokyo
    label: Tokyo
```

Please let me know if there’s interest, and I’d be happy to open a pull request and make any necessary changes to align with project standards.
