### ISSUE TITLE
Page Specific Authentification

### ISSUE THREAD

**Issue by louis-thevenet** [glanceapp/glance#694]
### Description

> What problem would this feature solve?

I'd love to share my Glance instance with people but it has a private page.

It would be great if we could configure a list of allowed users for each page.

> If applicable, what would the configuration for this feature look like?

```yaml
pages:
  - name: Private
    allowed-users:
      - admin
      - friend
    columns: ...
```
