### ISSUE TITLE
Target option for monitor widget

### ISSUE THREAD

**Issue by septechx** [glanceapp/glance#696]
### Description

Add a target option (like in the bookmarks widget) to allow opening services in the same tab correctly when using glance as a new tab page in a browser.

Example:
```yaml
- type: monitor
  cache: 1m
  title: Services
  sites:
    - title: Jellyfin
      url: https://jellyfin.yourdomain.com
      icon: /assets/jellyfin-logo.png
      same-tab: true
      target: _parent
```
