### ISSUE TITLE
Search Suggestions so that Google, DDG, and etc. have search suggestions.

### ISSUE THREAD

**Issue by rhijjawi** [glanceapp/glance#700]
### Description

Most search services already provide an API for Search Suggestions, for example:
[https://www.google.com/complete/search?client=chrome&q={QUERY}](https://www.google.com/complete/search?client=chrome&q=example)
```json
[
  "example",
  [
    "example deutsch",
    "examples",
    "https://example.com"
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
  ],
  [],
  {
    "google:clientdata": {
      "bpc": false,
      "tlw": false
    },
    "google:suggestrelevance": [
      602,
      601,
      600,
      561,
      560,
      559,
      558,
      557,
      556,
      555,
      554,
      553,
      552,
      551,
      550
    ],
    "google:suggestsubtypes": [
      [
        512
      ],
      [
        512
      ],
      [
        44
      ],
      [
        512
      ],
      [
        512
      ],
      [
        512
      ],
      [
        512
      ],
      [
        512
      ],
      [
        512
      ],
      [
        512
      ],
      [
        512
      ],
      [
        512
      ],
      [
        512
      ],
      [
        512
      ],
      [
        512
      ]
    ],
    "google:suggesttype": [
      "QUERY",
      "QUERY",
      "NAVIGATION",
      "QUERY",
      "QUERY",
      "QUERY",
      "QUERY",
      "QUERY",
      "QUERY",
      "QUERY",
      "QUERY",
      "QUERY",
      "QUERY",
      "QUERY",
      "QUERY"
    ],
    "google:verbatimrelevance": 1300
  }
]
```

**Comment by rhijjawi** [comment]
Would like to clarify I can get started on an implementation for this;

The idea is have a config such as below, and render the results.
```yaml
- type: search
   search-engine: google
   suggestions: true
   bangs:
       - title: YouTube
       shortcut: "!yt"
       suggestions: true
       url: https://www.youtube.com/results?search_query={QUERY} #Since hardcoded URL AND suggestions is true, needs suggestions_url
       suggestions_url: https://www.google.com/complete/search?client=chrome&ds=yt&q={QUERY}
```
