### ISSUE TITLE
Fails to render RSS feeds with no link

### ISSUE THREAD

**Issue by paulkakell** [glanceapp/glance#708]
### Description

How did you install Glance? (Docker container, manual binary install, etc)
**- Docker**
Which version of Glance are you using?
**0.8.3**
Include the relevant parts of your glance.yml if applicable (widget, data source, properties used, etc)
          **- type: rss
            title: US National Debt - Updated Daily
            cache: 1d
            feeds:
              - url: https://treasurydirect.gov/NP_WS/debt/feeds/recent**
Include any relevant logs or screenshots if applicable
**ERROR Failed to get RSS feed url=https://treasurydirect.gov/NP_WS/debt/feeds/recent error="unexpected status code 406 from https://treasurydirect.gov/NP_WS/debt/feeds/recent"**
Is the issue specific to a certain browser or OS?
**No**
Steps to reliably reproduce the issue
**Setup a RSS feed which does not contain a link.  The data source above is an example**
Are you hosting Glance on a VPS?
**confirmed not working on both VPS and residential**
Anything else you think might be relevant

**Comment by svilenmarkov** [comment]
This looks like an issue with the feed itself rather than Glance, since it's being exceptionally pedantic about what `Accept` header you give it. You'll need to manually add that header to your `glance.yml`:

```yml
- type: rss
  feeds:
    - url: https://treasurydirect.gov/NP_WS/debt/feeds/recent
      headers:
        # Fake an Accept header that a browser might send, which seems to work
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
```
