### ISSUE TITLE
[Feature Request] [Enhancement] Add Github Trending Pages

### ISSUE THREAD

**Issue by robertgro** [glanceapp/glance#72]
I really appreciate the idea of having such a dashboard combining several services across different providers. 

Please add

https://github.com/trending

To the list. This is how I found your repo. 

Thank you for the effort. Kind regards!

**Comment by yefoenix** [comment]
Maybe Rss Feeds work
https://mshibanami.github.io/GitHubTrendingRSS/

**Comment by robertgro** [comment]
Cool thx. Sorry for not providing a rss feed.

**Comment by aruiplex** [comment]
Here is the configure I used:

```yaml
          - type: rss
            limit: 500
            title: Github Daily Trending
            collapse-after: 3
            cache: 3h
            style: vertical-cards

            feeds:
              - url: https://mshibanami.github.io/GitHubTrendingRSS/daily/all.xml
                title: Github Daily Trending All
             
      
          - type: rss
            limit: 500
            title: Github Weekly Trending
            collapse-after: 3
            cache: 3h
            style: vertical-cards
            feeds:
              - url: https://mshibanami.github.io/GitHubTrendingRSS/weekly/all.xml
                title: Github Weekly Trending All


          - type: rss
            limit: 500
            title: Github Monthly Trending
            collapse-after: 3
            cache: 3h
            style: vertical-cards
            feeds:
              - url: https://mshibanami.github.io/GitHubTrendingRSS/monthly/all.xml
                title: Github Monthly Trending All
```
