### ISSUE TITLE
Unable to update theme

### ISSUE THREAD

**Issue by michaelwschultz** [glanceapp/glance#728]
### Description

I've tried updating the default theme, adding custom themes, nothing seems to change even after reloading the container.

0.8.4 installed via Docker locally

```
- name: Home

  theme:
    background-color: 229 19 23
    contrast-multiplier: 1.2
    primary-color: 222 74 74
    positive-color: 96 44 68
    negative-color: 359 68 71

  columns:
     etc...
```
