### ISSUE TITLE
HTML widget inside Group doesn't have default title

### ISSUE THREAD

**Issue by ralphocdol** [glanceapp/glance#735]
### Description
As stated in the Title

```yml
- type: group
  widgets:
    - type: html
      # title: when title is omitted
      source: |
        <div>Test1</div>
    - type: html
      title: title of test2
      source: |
        <div>Test2</div>
```

![Image](https://github.com/user-attachments/assets/d4f018f5-986b-47a0-8f44-0fd5848985aa)
