### ISSUE TITLE
Unable to set theme

### ISSUE THREAD

**Issue by varadins** [glanceapp/glance#738]
### Description

I have edited the glance.yml file to include the Tucan theme.  I have saved the file, and cleared my cache.  The theme does not apply and is not visible under the theme switcher.  The documentation is not clear that I needed to add the theme to glance.yml 

Here is my glance.yml

server:
  assets-path: /app/assets

theme:
  background-color: 50 1 6
  primary-color: 24 97 58
  negative-color: 209 88 54
  # Note: assets are cached by the browser, changes to the CSS file
  # will not be reflected until the browser cache is cleared (Ctrl+F5)
  #custom-css-file: /assets/user.css

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  - $include: home.yml

**Comment by svilenmarkov** [comment]
Are there any errors in the logs and have you tried restarting the container?

**Comment by varadins** [comment]
Confirmed latest version.

Since I don't have a configuration - I could just blow it all away and restart.

```
  GNU nano 7.2                                            home.yml                                                      

        - type: twitch-channels
          channels:
            - theprimeagen
            - j_blow
            - piratesoftware
            - cohhcarnage
            - christitustech
            - EJ_SA

    - size: full
      widgets:
        - type: group
          widgets:
            - type: hacker-news
            - type: lobsters

        - type: videos
          channels:
            - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
            - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
            - UCsBjURrPoezykLs9EqgamOA # Fireship
            - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
            - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium

        - type: group
          widgets:
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true

    - size: small
      widgets:
        - type: weather
          location: London, United Kingdom
          units: metric # alternatively "imperial"
          hour-format: 12h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true

        - type: markets
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: BTC-USD
              name: Bitcoin
            - symbol: NVDA
              name: NVIDIA
            - symbol: AAPL
              name: Apple
            - symbol: MSFT
              name: Microsoft

        - type: releases
          cache: 1d
          # Without authentication the Github API allows for up to 60 requests per hour. You can create a
          # read-only token from your Github account settings and use it here to increase the limit.
          # token: ...
          repositories:
            - glanceapp/glance
            - go-gitea/gitea
            - immich-app/immich
            - syncthing/syncthing
```
