### ISSUE TITLE
Specific RSS Feed stopped working

### ISSUE THREAD

**Issue by cinvokesec** [glanceapp/glance#741]
### Description

Glance Install: 0.8.4 manual binary install
Affected portion of YML file:
```
        widgets:
            - type: rss
              title: Latest Breaches
              feeds:
                  - url: https://haveibeenpwned.com/feed/breaches/
                    title: HaveIBeenPwned Lateset Breaches
                    limit: 8
```

Site is hosted on DigitalOcean.

I have a site with several RSS/Atom feeds. One specific feed from HaveIBeenPwned stopped working a few weeks ago. On the site it just shows an error that says "failed to retrieve any content". 

If I view the JournalCTL of my Glance app service it gives the error:
`ERROR Failed to get RSS feed url=https://haveibeenpwned.com/feed/breaches/ error="Failed to detect feed type"`

I've run the feed through several validators but there wasn't any critical issues:

![Image](https://github.com/user-attachments/assets/fc8bd77c-1027-4c0f-8724-c9bffce0c69c)

I've tried following steps on #691 by adding a browser User-Agent and the If-None-Match and If-Modified-Since headers but still no luck.

To be clear: this feed DID work before. I did not update Glance or do anything to the site that would cause it to break. I don't think the IP is blocked since I can performa successful Curl from the machine.

I'm trying to determine if this is an issue with how Glance handles feeds. 
The only thing I can think of is that utf-16 encoding isn't being handled properly, but I have no idea how to validate that. Any help figuring this out would be appreciated.
