### ISSUE TITLE
Multi-file configuration

### ISSUE THREAD

**Issue by p5** [glanceapp/glance#79]
Hey!

First off, I wanted to say this is a great project, and while I only found it recently, I have already recommended it to many others who are looking for an all-in-one homepage for all their news, links and media.

I would like to propose a configuration option which allows users to compose their configuration from multiple YAML files.  This allows someone to ship a default configuration, but also allow users to extend the configuration without touching the basic config.  

An example of how this could be used is a system-wide configuration file in `/etc/glance/glance.yaml`, and user-specific configurations in `$HOME/.config/glance.yaml` which extends the system config.  This could be additional pages, themes etc.

**Comment by AMS003010** [comment]
+1 to this. Love the idea. That would actually make the application more flexible on the client side.

**Comment by svilenmarkov** [comment]
Hey, thanks for the idea and for supporting the project! 

This would be difficult as the YAML spec doesn't have a standardized way of importing files which leaves me with figuring out a way of specifying which things should be inherited and which should get overwritten. 

For example, if you had this inside your base `glance.yml`:
```yml
pages:
  - name: Home
    columns:
      - size: full
        widgets:
          - type: reddit
```

And this inside your user configuration which extends the base:
```yml
pages:
  - name: Home
    columns:
      - size: full
        widgets:
          - type: reddit
            sort-by: new
```

What should happen? Should you end up with two Reddit widgets? Should the existing one inherit the new properties? What if you want to be able to do both in different scenarios, how would you achieve that?
