### ISSUE TITLE
Text overflowing

### ISSUE THREAD

**Issue by steveiliop56** [glanceapp/glance#86]
So I just noticed that in my reddit sidebar the text was overflowing going outside the designated spot. Here is a screenshot: 

<img width="301" alt="image" src="https://github.com/glanceapp/glance/assets/106091011/bc42b62e-9b8b-4c47-869f-9a0f1a244187">

*It is always programmer humor lol*

**Comment by svilenmarkov** [comment]
Hey, thanks for reporting this! 

This has now been fixed and it'll be out with the next release. In the meantime, you can override the title for each feed in your config to something shorter:

```yaml
- type: rss
  feeds:
    - url: ...
      title: Shorter Name
```
